	function InnGen(){
    	var langue = document.getElementById('langue_choisi').value;
        if(langue == "1"){
          var Establishment = ['Hostel','Inn','Tavern','Brothel','Boarding House','Casino','Hotel','Guest Room'];
          var Comfort = ['Squalid (1 SP)','Poor (2 SP)','Modest (5 SP)','Respectable (1 GP)','Comfortable (2 GP)','Wealthy (4 GP)','Lavish (6 GP)','Royal (10 GP)'];
          var Innkeeper = ['Dwarf','Human/Half-Elf','Tiefling','Gnome','Half-Orc','Dragonborn','Elf','Halfling'];
          var Personality = ['Old, cranky, and not fond of visitors','Nervous, as if they’re hiding something','Loud and boisterous: the life of every party','Obsessed with cleanliness and hates even the sight of mud','Just trying to get to the end of their shift','Always drunk, regardless of the time of day','Knows Common perfectly well, but refuses to speak it','Exceedingly competent and professional'];
          var Feature = ["A massive portrait of the innkeeper’s father hangs behind the front desk. The eyes follow you wherever you go.","There’s an entrance to an underground cavern system hidden in the basement.","There are messages in Thief’s Cant written under some of the beds directing the reader to nearby dead-drops for loot.","A ghost wanders the halls at night, and occasionally during the day as well.","One of the rooms is always locked. The actual owner is kept tied up inside at all times.","A local crime boss has made this establishment their base of operations against the wishes of the owner and the staff.","There’s a mimic loose somewhere in the establishment, but the owner isn’t quite sure where.","Meals are disproportionately cheap, but the meat doesn’t taste like anything the party has ever eaten before."];
		  var Comfort2 = ["You’re sleeping on a pile of hay in the stables, and your bathroom is a bucket, but at least you’re out of the rain.","Just because you can run an inn doesn’t mean that you should. These places always have something about them that makes the experience unpleasant, like overflowing chamber pots or a rat infestation. You do technically have a bed, but you may be sharing it with one or more people.","The accommodation level for the average village inn. Well-kept, but unfussy. The mattresses are still stuffed with straw, and the blankets are scratchy, but everything is clean, and you don’t have to worry about vermin.","","Once you get into slightly larger towns, you’ll start to find places that cater to the traveling merchant class. There are occasional feather beds, softer pillows, and meals that can be brought to your room. It isn’t exactly fancy, but it’s certainly a step above average.","This is when you get your own private bathroom. These are often the nicest accommodations that you can find in small cities. They can feel a little bit pretentious and stuffy at times, but it doesn’t make the mattresses any less comfortable.","The favorite accommodation level of rich merchants and petty aristocrats. It’s roughly equivalent to the level of most boutique luxury hotels. The thread counts are high, everything is stuffed with goose down, and service is always quick. Forget a private bathroom; in places like this, you have your own bath tub.","Equivalent to the presidential suite at a five-star hotel. There are multiple rooms, dedicated serving staff, and as much alcohol as you can drink. This level of accommodation can only be found in large cities, and cater to an elite clientele. If your party isn’t well-dressed, they may not be allowed inside no matter how much money they can wave around."];
        }
        else{
          var Establishment = ['Auberge de jeunesse', 'Auberge', 'Taverne', 'Bordel', 'Pension de famille', 'Casino', 'Hôtel', "Chambre d'hôtes"];
          var Comfort = ['Misérable (1 SP)','Pauvre (2 SP)','Modeste (5 SP)','Respectable (1 GP)','Confortable (2 GP)','Riche (4 GP)','Somptueux (6 GP)','Royal (10 GP)'];
          var Innkeeper = ['Nain','Human/Demi-Elf','Tieflin','Gnome','Demi-Orc','Dragonborn','Elfe','Halflin'];
          var Personality = ["Vieux, grincheux et n'aimant pas les visiteurs", "Nerveux, comme s'ils cachaient quelque chose", "Bruyant et agité: la vie de chaque fête", "Obsédé par la propreté et déteste même la vue de la boue", "Essaie juste de finir sa journée de travail", "Toujours ivre, quelle que soit l'heure de la journée","Connaît parfaitement le commun, mais refuse de le parler","Extrêmement compétent et professionnel"];
          var Feature = ["Un portrait massif du père de l'aubergiste est accroché derrière la réception. Les yeux vous suivent partout où vous allez.", "Il y a une entrée dans un système de cavernes souterraines caché dans le sous-sol.", "Il y a des messages écrits en argot de voleur sous certains des lits qui dirige le lecteur vers des tombes mortes à proximité pour récupérer le butin. "," Un fantôme se promène dans les couloirs la nuit, et parfois aussi pendant la journée. "," Une des chambres est toujours fermée. Le propriétaire actuel est attaché à l'intérieur. "," Un patron du crime local a fait de cet établissement leur base d'opérations contre la volonté du propriétaire et du personnel. "," Il y a un mimétisme quelque part dans l'établissement, mais le propriétaire n'est pas tout à fait sûr où. "," Les repas sont disproportionnellement bon marché, mais la viande n'a pas le même goût de tout ce que le groupe a jamais mangé auparavant. "];
		  var Comfort2 = ["Vous dormez sur un tas de foin dans les étables, et votre salle de bain est un seau, mais au moins vous êtes à l'abri de la pluie.", "Ce n'est pas parce que vous pouvez gérer une auberge que vous devriez. Ces endroits ont toujours quelque chose à leur sujet qui rend l'expérience désagréable, comme des pots de chambre débordants ou une infestation de rats. Vous avez techniquement un lit, mais vous pouvez le partager avec une ou plusieurs personnes. "," La qualité de l'herbergement pour cette auberge de village est moyenne. Bien entretenu, mais sans prétention. Les matelas sont encore bourrés de paille et les couvertures sont éraflées, mais tout est propre et vous n'avez pas à vous soucier de la vermine. "," "," Une fois que vous arrivez dans des villes un peu plus grandes, vous commencez à trouver des endroits adaptés à la classe des marchands ambulants. Il y a parfois des lits en plumes, des oreillers plus moelleux et des repas qui peuvent être apportés dans votre chambre. c'est certainement un cran au-dessus de la moyenne. "," C'est alors que vous avez votre propre salle de bain privée. Ce sont souvent les plus beaux hébergements que vous pouvez trouver dans les petites villes. Ils peuvent parfois se sentir un peu prétentieux et étouffants, mais cela ne rend pas les matelas moins confortables. "," Le niveau d'hébergement préféré des riches marchands et des petits aristocrates. Il est à peu près équivalent au niveau de la plupart des hôtels de luxe de charme. Le nombre de fils est élevé, tout est bourré de duvet d'oie et le service est toujours rapide. Oubliez une salle de bain privée; dans des endroits comme celui-ci, vous avez votre propre baignoire. "," Equivalent à la suite présidentielle d'un hôtel cinq étoiles. Il y a plusieurs salles, un personnel de service dévoué et autant d'alcool que vous pouvez en boire. Ce niveau d'hébergement ne peut être trouvé que dans les grandes villes et s'adresse à une clientèle d'élite. Si votre groupe n'est pas bien habillé, il se peut qu'ils ne soient pas autorisés à l'intérieur, peu importe le montant d'argent qu'ils peuvent faire circuler. "];
        }
        var Rand1 = Math.floor(Math.random() * Math.floor(8));
        var Rand2 = Math.floor(Math.random() * Math.floor(8));
        var Rand3 = Math.floor(Math.random() * Math.floor(8));
        var Rand4 = Math.floor(Math.random() * Math.floor(8));
        var Rand5 = Math.floor(Math.random() * Math.floor(8));
        var El1 = Establishment[Rand1];
        var El2 = Comfort[Rand2];var El2_2 = Comfort2[Rand2];
        var El3 = Innkeeper[Rand3];
        var El4 = Personality[Rand4];
        var El5 = Feature[Rand5];
		
		
        if(langue == "1"){       
			document.getElementById('résultat_aff').innerHTML = "Establishment: "+El1+"<br>Comfort: "+El2+". "+El2_2+"<br>Innkeeper: "+El3+". "+El4+".<br>Feature: "+El5;
		}
		else{
			document.getElementById('résultat_aff').innerHTML = "Etablissement: "+El1+"<br>Confort: "+El2+". "+El2_2+"<br>Barman: "+El3+". "+El4+".<br>Particularité: "+El5;
		}
    }
	
function LootGen(){
	var langue = document.getElementById('langue_choisi').value;
    var Nbre = Math.floor(Math.random() * Math.floor(10))+1;
	if(langue == "1"){
		var Loot = ["Partially used journal | Strange statuette | Black magic doll","Wrapped turkey leg  | Fingernail shavings | Strange mask","Locket | Pot of ashes | Strange circlet","Hand mirror | Choke collar | Elf ear","Instrument | Taxidermied mouse | Wooden stake with runes","Guild badge | Lock of hair | Book bound in skin","Thieves tools | Strange letter | Monster part (GM’s choice)","Pelt of some kind | Instructions for a trade | Unit of glowing ore","Random book | Fragment of stone | Hallucinogenic fungus","Waterskin | Pocket full of gravel | Preserved organ in a jar","Silver ring | Scribbled fortunes | Vial of blood","Manacles | Ball of clay | Records of black magic","Bedroll | Folk remedy for something | Bloody hand","Dice | Mechanical piece | Bag of teeth","Business ledger | Scrimshawed bone | Monster skull","Cheap wine | Ladies’ underwear | Notes about the players","Map of the area | Strange dried meat | Map to an unknown place","Flask of spirits | Blackmail material | Dead bird","Lucky charm of some form | Marital aids | Feverish sketches","Gwent deck | Odd dream journal | Insane notes","Tent | Fish bones | Illegible scroll","Sketch of a person | Note with one number | Symbol written in blood","Soap | Tooth | Strange jade statuette","Holy symbol | Worn out shoe | A lock of blonde hair","Flint & steel | Reins | A strange, empty lamp","Whistle | List of people | Scrimshawed human bone","Sun stone | Five iron nails | Iron shoes","Shopping list | Strange sea shells | Human skull","1 Unit of feathers | Strange poetry | Censer full of caked blood","Dried meat or salted fish | Extremely mouldy bread | Tattooed skin","Pouch of spices | Unknown key | Ritual dagger","Empty vial | Paper with lipstick marks | Black magic ring","Chalk | Arrowhead | Severed tongue"];
	}else{
		var Loot = ["Journal partiellement utilisé | Statuette étrange | Poupée magique noire", "Cuisse de dinde enveloppée | Copeaux d'ongle | Masque étrange", "Médaillon | Pot de cendres | Cercle étrange", "Miroir à main | Collier étrangleur | Oreille d'elfe" , "Instrument | Souris taxidermée | Pieu en bois avec runes", "Badge de guilde | Mèche de cheveux | Livre lié dans la peau", "Outils de voleurs | Lettre étrange | Partie de monstre (au choix du MJ)", "Peau d'animal | Instructions pour un métier | Unité de minerai rougeoyant "," Livre aléatoire | Fragment de pierre | Champignon hallucinogène "," Gourde | Poche pleine de gravier | Organe conservé dans un bocal "," Bague en argent | Fortunes griffonnées | Fiole de sang "," Menottes | Boule d'argile | Registres de magie noire "," Rouleau de lit | Remède populaire pour quelque chose | Main sanglante "," Dés | Pièce mécanique | Sac de dents "," Grand livre commercial | Os gratté | Crâne de monstre "," Vin pas cher | Sous-vêtements féminins | Notes sur les joueurs "," Carte de la région | Étrange viande séchée | Carte d'un endroit inconnu "," Flacon de spiritueux | Matériel de chantage | Oiseau mort " , "Porte-bonheur d'une certaine forme | Aides conjugales | Croquis fébriles "," Deck Gwent | Journal de rêve étrange | Notes insensés "," Tente | Arêtes de poisson | Parchemin illisible "," Esquisse d'une personne | Remarque avec un chiffre | Symbole écrit dans le sang "," Savon | Dent | Étrange statuette de jade "," Symbole sacré | Chaussure usée | Une mèche de cheveux blonds "," Allume feu | Rênes | Une étrange lampe vide "," Sifflet | Liste de personnes | Os humain écorcé "," Pierre du soleil | Cinq clous de fer | Chaussures de fer "," Liste de courses | Coquilles de mer étranges | Crâne humain "," 1 unité de plumes | Poésie étrange | Encensoir plein de sang séché "," Viande séchée ou poisson salé | Pain extrêmement moisi | Peau tatouée "," Poche d'épices | Clé inconnue | Dague rituelle "," Flacon vide | Papier avec des marques de rouge à lèvres | Anneau de magie noire "," Craie | Pointe de flèche | Langue coupée "];
	}
	var Item = "";
	for (let i = 0; i < Nbre; i++) {
		var Rand = Math.floor(Math.random() * Math.floor(33));
		var Item = Item+Loot[Rand]+"<br>";
	}
	document.getElementById('résultat_aff2').innerHTML = "Item: "+Nbre+"<br><div style='margin-left:50px;'>"+Item+"</div>";		
}

function ContractGen(){
	var langue = document.getElementById('langue_choisi').value;
	var Monster = ['Specter','Cursed One','Hybrid','Insectoid','Elementa','Relict','Ogroid','Draconid','Necrophage','Vampire'];
	var MDifficulty = ['Easy','Medium','Hard'];
	var MComplexity = ['Simple','Difficult','Complex'];
	if(langue == "1"){
		var Location = ['A Forest','A building','An Abandoned Building','A Coast','The Mountains','The City','A Graveyard','A Hamlet','Along the River','A Cave'];
		var Twisted = ["The Monster Is Fake","It Is All A Curse","The Monster Is Already Dead","It Isn’t What You Think","EmployerWants It Caught","The Employer Is To Blame For It All","The Monster Is Harmless","It Is A Trap For You","It Was More Than You Were Told","A Mage Is Behind It All"];
		var Employer = ["A Peasant or Ealdorman","A Guard or Witch Hunter","A Merchant","A Scholar or Noble","A Mage","A King, Queen, Duke or Duchess"];
		var Pay = ["The Employer is unable to, or tries not to Pay","The Employer Offers a Trade","The Employer Pays less than Agreed","The Employer pays Exactly as Agreed","The Employer Pays More than Agreed","The Employer tries to have you killed","The Employer is nowhere to be found"];
		var Complication = ["Bandits are hunting the monster","A Witcher is already hunting it","It can't be killed normally","The Employer has died","Monster has trapped hostages","Extra Twist. Roll on Twist Table"];

		var Twist = ['There is a twist: ','No twist.'];
	}else{
		var Location = ['une forêt','un batiment','un batiment abandonné','la côte','les montagnes','en ville','un cimetierre','un hameau','le long de la rivière','une grotte'];
		var Twisted = ["Le monstre est faux", "C'est une malédiction", "Le monstre est déjà mort", "Ce n'est pas ce que vous pensez", "L'employeur veut qu'il soit attrapé", "L'employeur est à blâmer pour tout cela","Le monstre est inoffensif","C'est un piège","C'était plus que ce qu'on vous aviez dit","Un mage est derrière tout cela"];
		var Employer = ["Un paysan ou un Ealdorman", "Un garde ou un chasseur de sorcières", "Un marchand", "Un érudit ou un noble", "Un mage", "Un roi, une reine, un duc ou une duchesse"];
		var Pay = ["L'Employeur ne peut pas ou essaie de ne pas payer", "L'Employeur propose un échange", "L'Employeur paie moins que convenu", "L'Employeur paie exactement comme convenu", "L'Employeur paie plus que convenu "," L'Employeur essaie de vous faire tuer "," L'Employeur est introuvable "];
		var Complication = ["Des bandits chassent le monstre", "Un sorceleur le chasse déjà", "Il ne peut pas être tué normalement", "L'Employeur est mort", "Le monstre a piégé des otages", "Extra Twist. sur Twist Table "];
		var Twist = ["Il y a un retournement de situation: ","Il n'y a pas de retournement de situation."];
	}
	var Rand1 = Math.floor(Math.random() * Math.floor(10));
	var Rand2 = Math.floor(Math.random() * Math.floor(10));
	var Rand3 = Math.floor(Math.random() * Math.floor(10));
	var Rand4 = Math.floor(Math.random() * Math.floor(10));
	var Rand5 = Math.floor(Math.random() * Math.floor(10));
	var Rand6 = Math.floor(Math.random() * Math.floor(10));
	var Rand7 = Math.floor(Math.random() * Math.floor(6));
	var Rand8 = Math.floor(Math.random() * Math.floor(10));
	var Rand9 = Math.floor(Math.random() * Math.floor(8));
	
	var El1 = Monster[Rand1];
	if(Rand2 < 4){var El2 = MDifficulty[0];}else if(Rand2 > 7){var El2 = MDifficulty[2];}else{var El2 = MDifficulty[1];}
	if(Rand3 < 4){var El3 = MComplexity[0];}else if(Rand3 > 7){var El3 = MComplexity[2];}else{var El3 = MComplexity[1];}
	var El4 = Location[Rand4];
	if(Rand5 < 4){var El5 = Twist[0]+Twisted[Rand6];}else{var El5 = Twist[1];}
	var El7 = Employer[Rand7];
	var El8 = Pay[Rand8];
	if(Rand8 < 7 && Rand8 > 2){var El8 = Pay[3];}if(Rand8 == 7){var El8 = Pay[4];}if(Rand8 == 8){var El8 = Pay[5];}if(Rand8 == 9){var El8 = Pay[6];}
	if(Rand9 < 2){var El9 = Complication[0];}if(Rand9 < 4){var El9 = Complication[1];}if(Rand9 == 4){var El9 = Complication[2];}if(Rand9 == 5){var El9 = Complication[3];}if(Rand9 > 5){var El9 = Complication[4];}

	
    if(langue == "1"){       
		document.getElementById('résultat_aff3').innerHTML = "Monster: "+El1+" ["+El2+" - "+El3+"]<br>Location: "+El4+"<br>"+El5+"<br>Employer: "+El7+". "+El8+".<br>Complication (Optionally): "+El9;
	}else{
		document.getElementById('résultat_aff3').innerHTML = "Monstre: "+El1+" ["+El2+" - "+El3+"]<br>Localisation: "+El4+"<br>"+El5+"<br>Employeur: "+El7+". "+El8+".<br>Complication (Optionnel): "+El9;
	}
	
}

function LifeGen(){
	var langue = document.getElementById('langue_choisi').value;
		var NKOrigin = ["Redania","Kaedwen","Temeria","Aedirn","Lyria & Rivia","Kovir & Poviss","Skellige","Cidaris","Verden","Cintra"];
		var EOrigin = ["Dol Blathanna","Mahakam"];
	if(langue == "1"){
		var Region = ['Northern Kingdoms','Nilfgaard','Elderlands'];
		var NOrigin = ["Vicovaro","Angren","Nazair","Mettina","Mag Turga","Gheso","Ebbing","Maecht","Gemmeria","Etolia","The Heart of Nilfgaard"];
		var Family_Fate1 = ["Your family was scattered to the winds by the wars and you have no idea where most of them are.","Your family was imprisoned for crimes or on trumped-up charges. You were the only one to escape. You may want to free them...or maybe not.","Your family house was cursed and now either crops won’t grow or specters roam the halls. It became too dangerous for you to stay in this home.","With so many wars your family’s livelihood was destroyed. Your family turned to crime to survive.","Your family accumulated a huge debt through gambling or favors from others. You need money desperately.","Your family has fallen into a feud with another family. You may not even remember why this feud started in the first place.","Due to some action or inaction your family has become hated in your home town and now no one there wants to have anything to do with them.","One day everything you had was ripped away by a bandit mob. Your family was massacred, leaving you entirely alone.","Your family has a deep, dark secret that if discovered would ruin you all completely. You can decide what this secret is, or the Game Master can decide.","Your family has come to despise each other. No one you grew up with will talk with each other any more and you’re lucky to get a passing hello from your siblings."];
		var Family_Fate2 = ["Your family was indentured for crimes against the Empire or on trumped-up charges. Only you escaped.","Your family was exiled to the Korath Desert and you likely spent most of your early life struggling to survive in the deadly wasteland.","Your family was killed by a rogue mage who either had a vendetta against your family, or just wanted blood. Either way, you are alone.","Your family disappeared and you have no idea where they went. One day they just up and left.","Your family was executed for treason against the Empire. You were the only one to escape this fate.","Your family was stripped of its title for some reason. You were evicted from your home and left scrambling to survive among the un-washed masses.","Your family name was tarnished by a magic relative who flaunted their magical gift disgracefully like a Northern mage.","You disgraced your family in the eyes of the Empire. Something you did or failed to do has ruined your personal name and harmed your family.","Your family has a deep, dark secret that if discovered would destroy them and their name forever. You must protect this secret with your life. ","Your family was assassinated. They may have been in the way of someone’s plan or they may have been used to get at someone more powerful. Either way, your family is gone now."];
		var Family_Fate3 = ["Your family were marked as human sympathizers and are not particularly loved in their homeland.","Your family was ostracized for dissenting opinions and now people won’t socialize with you or your family at all.","Your family died in the Northern Wars. They may have actually fought in the war, or were casualties of war who just happened to get in the way.","Your family has been caught in a feud for centuries. You may not remember why this feud started, but it is dire.","Your family was stripped of its title for some reason. You were evicted from your home and left scrambling to survive.","Your family turned to raiding human settlements early in your life to get food and perhaps strike back at the humans.","Your family house is haunted. Most likely this is because your home was the site of many, many deaths during the war against humans.","Your family has been split by a human in-law who was brought into your family by a sibling or relative. Some of your family like them and some hate them.","Your family was killed by humans who thought they were Scoia’tael. They may have been slaughtered or hung with no court proceedings or trials.","Your family is descended from an infamous traitor. It taints your family’s interactions with others of the elder races and has made living in the elderland difficult."];
		var Parental_Fate1 = ["One or more of your parents were killed in the Northern Wars. Most likely your father, but it is also possible that your mother fought or was a casualty.","One or more of your parents left you in the wilderness to fend for yourself. Maybe they couldn’t afford to keep you; maybe you were an accident.","One or more of your parents were cursed by a mage or due to the intense hatred of someone they encountered. The curse took their life.","One or more of your parents sold you for coin, or perhaps traded you for some goods or service. Your parents needed the money more than you.","One or more of your parents joined a gang. You saw this gang often and were sometimes forced to work with them.","One or more of your parents were killed by monsters. It is your decision as to what they may have fallen prey to.","One or more of your parents were falsely executed. They may have been a scapegoat for something or just in the wrong place. ","One or more of your parents died of a plague. There was nothing that could be done but try to ease their passing.","One or more of your parents defected to Nilfgaard. They may have been given a deal for information or they may just have jumped the border.","One or more of your parents were kidnapped by nobles. Likely it was your mother, who attracted the attention of a local lord or his son."];
		var Parental_Fate2 = ["Your father died in one of the Northern Wars. He may have already been in the military or he may have been conscripted into service during that war.","One or more of your parents were poisoned. This may have been the work of a professional rival, or it may have been to get your parents out of the way.","The secret police took your parent or parents for ‘questioning.’ The next week their bodies were found hung in the streets of the city.","One or more of your parents were killed by a rogue mage. Most likely they tried to turn the mage in question in to the Empire and paid the price.","One or more of your parents were imprisoned for unlawful magic. Maybe they actually commited the crime or maybe it was a setup.","One or more of your parents were exiled to the Korath Desert. Likely they committed a major crime but killing them would cause trouble.","One or more of your parents were cursed by a mage. The mage likely had a vendetta against them.","Your parents simply left you one day. You may not even know why they did it. One day your parents just disappeared.","One or more of your parents were enslaved. They either commited a crime against the Empire or were set up by a rival.","One or more of your parents were sent to the North as double agents. You likely don’t even know where they are now, but they’re serving the Emperor."];
		var Parental_Fate3 = ["One or more of your parents were accused of being Scoia’tael. The people around you give your parents sidelong glances.","One or more of your parents turned on your own people and sold out the elder races to the humans. Your parents are unwelcome in your homeland.","One or more of your parents killed themselves out of despair. With no hope of regaining the glory of the past, they gave up and ended it.","While traveling, one or more of your parents fell prey to human racism. They died in a pogrom and their bodies were displayed on pikes.","One or more of your parents have become obssessed with regaining the former glory of their race. They sacrifice everything for this cause.","One or more of your parents were exiled from your homeland. There are many possible reasons, from crime to dissenting opinons.","One or more of your parents were cursed. You can decide what this curse is or, the Game Master can decide.","Your parents gave you to another family so that you could survive, because they couldn’t care for you.","One or more of your parents joined the Scoia’tael in an attempt to get revenge on the humans who they see as ruining their lives.","One or more of your parents died in an ‘accident’. Most likely they made a powerful enemy that finally found a way to get rid of them."];
		var Family_Status1 = ["Aristocracy : You grew up in a noble manor with servants to wait on you, but you were always expected to behave and impress.","Adopted by a Mage : You were given to a mage at a young age. You lived in comfort but barely saw your caretaker, who was always busy.","Knights : You grew up in a manor where you learned to be a proper lady or lord. Your fate was set from birth.","Merchant Family : You grew up among merchants and you were always surrounded by yelling, haggling, and money.","Artisan Family : You grew up in an artisan’s workshop. Your days were  lled with the incessant sounds of creation, and o en long.","Entertainer Family : You grew up with a band of performers. You may have traveled or you may have performed at a theater.","Peasant Family : You grew up on a farm in the countryside. You didn’t have much to your name and your life was simple, but dangerous."];
		var Family_Status2 = ["Aristocracy : You grew up in a manor, training to be well-versed in the world of the court. The luxury was just your incentive.","High Clergy : You were raised among the clergy of the Great Sun. You grew up pious and always aware that the Church would guide you.","Knights : You grew up knowing that your duty was to the Emperor, and that all of your luxury was a reward for your eventual service. ","Artisan Family : You grew up in an artisan’s shop, learning to cra products for sale around the world. You learned the value of quality.","Merchant Family : You grew up selling products all around the Empire. You saw all kinds exotic of goods from all around the world.","Born into Servitude : You were born into servitude and lived in simple quarters. You owned very little and toiled often.","Peasant Family : You grew up on one of the thousands of farms across the Empire. You had little to your name but life was simple."];
		var Family_Status3 = ["Aristocracy : You grew up in a palace and were constantly reminded of the glory of the past. You were expected to live up to the legacy.","Noble Warrior : You grew up as a noble warrior’s child, expected to rise to your family’s reputation and to never dishonor your heritage.","Merchants : You grew up among traveling merchants. Life was dificult sometimes but non-human crafts are always valuable.","Scribe Family : You grew up as the child of scribes, recording and protecting as much elderfolk history as possible.","Entertainers : You grew up singing songs and performing plays. You worked backstage, helped write songs, and  xed instruments.","Artisan Family : You grew up in a family of artisans, visiting ancient palaces for inspiration and spending hours every day on projects.","Lowborn Family : You grew up in a lowborn family, tending to the manors of others or working small jobs around your home city."];
		var Clothing = ["A Uniform","Traveling Clothing","Fancy Clothing","Ragged Clothing","Utilitarian Clothing","Traditional Clothing","Revealing Clothing","Heavy Clothing","Strange Clothing","Flamboyant Clothing"];
		var Personality = ["Secretive","Rebellious","Violent","Idealistic","Contemplative","Stern","Deceptive","Friendly","Arrogant","Nervous"];
		var Hair = ["Long & Loose","Cropped Short","Self-Cut Short","Braided","Long & Wild","Bald","Uniformly Short","Ragged & Messy","Complicated Hairstyle","Shaven Sides"];
		var Affectations = ["Trophies","Rings & Jewlery","Trinkets","Tattoos","War Paint","Shadowy Cloak","Bright Bandanas","Eye Patch","Furs","Insignias & Plaques"];
		var Valued_Person = ["A Parent","A Sibling","A Lover ","A Friend","Yourself","A Pet","A Mentor","A Public Figure","A Personal Hero","No One"];
		var Valued = ["Money","Honor","Your Word","Hedonistic","Knowledge","Vengeance","Power","Love","Survival","Friendship"];
		var Feelings = ["People Are Tools to Be Used","Our Kind Are Fine but Plough the Rest","People Can Never Be Trusted","People Have to Prove themselves","Neutral","Neutral","People Are Great","Everyone Deserves to Die","People Are Hedonistic Swine","All Life Is Valuble"];
	}else{
		var Region = ['Royaumes du Nord','Nilfgaard','Terres Ancestrales'];
		var NOrigin = ["Vicovaro","Angren","Nazair","Mettina","Mag Turga","Gheso","Ebbing","Maecht","Gemmeria","Etolia","Le coeur de Nilfgaard"];
		var Family_Fate1 = ["Votre famille a été dispersée par les guerres et vous ne savez pas où se trouvent la plupart d'entre elles.","Votre famille a été emprisonnée pour des délits ou pour des accusations forgées de toutes pièces. Tu étais le seul à t'échapper. Vous voudrez peut-être les libérer ... ou peut-être pas.","Votre maison familiale a été maudite et maintenant les récoltes ne poussent plus et des spectres parcourent les couloirs. Il est devenu trop dangereux pour vous de rester dans cette maison.","Avec tant de guerres, le gagne-pain de votre famille a été détruit. Votre famille s'est tournée vers le crime pour survivre.","Votre famille a accumulé une énorme dette de jeux. Vous avez désespérément besoin d'argent.","Votre famille est morte dans une querelle avec une autre famille. Vous ne vous souvenez peut-être même pas pourquoi cette querelle a commencé...","En raison d'une action ou d'une inaction, votre famille est devenue détestée dans votre ville natale et maintenant personne là-bas ne veut rien avoir à faire avec eux.","Un jour, tout ce que vous aviez a été arraché par une bande de bandits. Votre famille a été massacrée, vous laissant entièrement seul.","Votre famille a un secret profond et sombre qui, s'il était découvert, vous ruinerait complètement. Vous pouvez décider quel est ce secret, ou le MJ peut décider.","Votre famille en est venue à se mépriser. Personne avec qui vous avez grandi ne vous reparlera et vous avez de la chance de recevoir le bonjour de vos frères et sœurs."];
		var Family_Fate2 = ["Votre famille a été condamné pour des crimes contre l'Empire ou pour de fausses accusations. Vous seul avez échappé.","Votre famille a été exilée dans le désert de Korath et vous avez probablement passé la majeure partie de votre jeunesse à lutter pour survivre dans ce désert mortel.","Votre famille a été tuée par un mage renégat qui a eu une vendetta contre votre famille ou qui voulait juste du sang. De toute façon, vous êtes seul.","Votre famille a disparu et vous ne savez pas où ils sont allés. Un jour, ils se sont levés et sont partis.","Votre famille a été exécutée pour trahison contre l'Empire. Vous étiez le seul à échapper à ce sort.","Votre famille a été dépouillée de son titre pour une raison quelconque. Vous avez été expulsé de votre domicile et vous avez dû survivre parmi le peuple.","Votre nom de famille a été terni par un parent magicien qui s'affiche honteusement comme un mage du Nord.","Vous avez déshonoré votre famille aux yeux de l'Empire. Quelque chose que vous avez fait ou omis de faire a ruiné votre nom personnel et a nui à votre famille.","Votre famille a un secret profond et sombre qui, s'il était découvert, les détruirait ainsi que leur nom pour toujours. Vous devez protéger ce secret avec votre vie.","Votre famille a été assassinée. Ils peuvent avoir gêné le plan de quelqu'un ou avoir été utilisé pour atteindre quelqu'un de plus puissant. De toute façon, votre famille est partie maintenant."];
		var Family_Fate3 = ["Votre famille était marquée comme des sympathisants humains et n'est pas particulièrement aimée dans sa patrie.","Votre famille a été ostracisée pour ses opinions dissidentes et maintenant les gens ne vont plus socialiser avec vous ou votre famille.","Votre famille est morte dans les guerres du Nord. Ils ont peut-être effectivement combattu pendant la guerre ou ont été des victimes de la guerre.","Votre famille est prise dans une querelle depuis des siècles. Vous ne vous souvenez peut-être pas pourquoi cette querelle a commencé, mais c'est terrible.","Votre famille a été dépouillée de son titre pour une raison quelconque. Vous avez été expulsé de votre domicile et laissé en difficulté pour survivre","Votre famille a pillé des établissements humains au début de votre vie pour obtenir de la nourriture et peut-être riposter contre les humains.","Votre maison familiale est hantée. C'est très probablement parce que votre maison a été le site de nombreux morts pendant la guerre contre les humains.","Votre famille a été divisée par un beau-père humain qui a été amené dans votre famille par un frère ou une sœur. Certains membres de votre famille les aiment et d'autres les détestent.","Votre famille a été tuée par des humains qui les prennaient pour des Scoia’tael. Ils peuvent avoir été abattus ou pendus sans procédure ni procès.","Votre famille est issue d'un traître infâme. Il entache les interactions de votre famille avec les autres races et rend la vie dans les terres ancestrales difficile."];
		var Parental_Fate1 = ["Un ou plusieurs de vos parents ont été tués dans les guerres du Nord. Très probablement votre père, mais il est également possible que votre mère se soit battue ou ait été une victime.","Un ou plusieurs de vos parents vous ont laissé seul dans les étendus sauvages. Peut-être qu'ils ne pouvaient pas se permettre de vous garder; vous étiez peut-être un accident.","Un ou plusieurs de vos parents ont été maudits par un mage ou à cause de la haine intense de quelqu'un qu'ils ont rencontré. La malédiction leur a pris la vie.","Un ou plusieurs de vos parents vous ont vendu pour de la monnaie ou vous ont peut-être échangé contre certains biens ou services. Vos parents avaient plus besoin d'argent que vous.","Un ou plusieurs de vos parents ont rejoint un gang. Vous avez vu ce gang souvent et avez parfois été obligé de travailler avec eux.","Un ou plusieurs de vos parents ont été tués par des monstres. C'est à vous de décider à quoi ils ont pu être la proie.","Un ou plusieurs de vos parents ont été exécutés à tort. Ils peuvent avoir été un bouc émissaire pour quelque chose ou simplement au mauvais endroit.","Un ou plusieurs de vos parents sont morts de la peste. Il n'y avait rien d'autre à faire que d'essayer d'achever leur souffrance.","Un ou plusieurs de vos parents ont fait défection à Nilfgaard. Ils ont peut-être obtenu un accord pour obtenir des informations ou ils ont peut-être simplement franchi la frontière.","Un ou plusieurs de vos parents ont été enlevés par des nobles. C'est probablement votre mère qui a attiré l'attention d'un seigneur local ou de son fils."];
		var Parental_Fate2 = ["Votre père est décédé dans l'une des guerres du Nord. Il a peut-être déjà été dans l'armée ou il peut avoir été enrôlé pendant cette guerre","Un ou plusieurs de vos parents ont été empoisonnés. Cela a peut-être été le travail d'un rival professionnel, ou cela a peut-être été pour écarter vos parents.","La police secrète a emmené votre ou vos parents pour un «interrogatoire». La semaine suivante, leur corps a été retrouvé pendu dans les rues de la ville.","Un ou plusieurs de vos parents ont été tués par un mage voyou. Ils ont très probablement essayé de remettre le mage en question et en ont payé le prix.","Un ou plusieurs de vos parents ont été emprisonnés pour magie illégale. Peut-être qu'ils ont réellement commis le crime ou peut-être que c'était une mise en scène.","Un ou plusieurs de vos parents ont été exilés dans le désert de Korath. Ils ont probablement commis un crime majeur, mais les tuer causerait des problèmes.","Un ou plusieurs de vos parents ont été maudits par un mage. Le mage avait probablement une vendetta contre eux.","Vos parents vous ont simplement quittés. Vous ne savez peut-être même pas pourquoi ils l'ont fait. Un jour, vos parents ont tout simplement disparu.","Un ou plusieurs de vos parents ont été réduits en esclavage. Ils ont commis un crime contre l'Empire ou ont été piégé par un rival.","Un ou plusieurs de vos parents ont été envoyés dans le Nord comme agents doubles. Vous ne savez probablement même pas où ils sont maintenant, mais ils servent l'Empereur."];
		var Parental_Fate3 = ["Un ou plusieurs de vos parents ont été accusés d’être Scoia’tael. Les gens autour de vous jettent des regards à vos parents.","Un ou plusieurs de vos parents se sont retournés contre votre propre peuple et ont vendu les races aînées aux humains. Vos parents ne sont pas les bienvenus dans votre pays d'origine.","Un ou plusieurs de vos parents se sont suicidés de désespoir. Sans espoir de regagner la gloire du passé, ils ont abandonné et y ont mis fin.","En voyage, un ou plusieurs de vos parents sont devenus la proie du racisme humain. Ils sont morts dans un pogrom et leurs corps ont été affichés sur des piques.","Un ou plusieurs de vos parents sont devenus obsédés par le fait de retrouver l'ancienne gloire de leur race. Ils ont tout sacrifié pour cette cause.","Un ou plusieurs de vos parents ont été exilés de votre patrie. Il existe de nombreuses raisons possibles, du crime aux opinions dissidentes.","Un ou plusieurs de vos parents ont été maudits. Vous pouvez décider de ce qu'est cette malédiction ou, le Game Master peut décider.","Vos parents vous ont donné à une autre famille pour que vous puissiez survivre, car ils ne pouvaient pas prendre soin de vous.","Un ou plusieurs de vos parents ont rejoint les Scoia’tael pour tenter de se venger des humains qu’ils considèrent comme ruinant leur vie.","Un ou plusieurs de vos parents sont décédés dans un «accident». Très probablement, ils se sont fait un ennemi puissant qui a finalement trouvé un moyen de s'en débarrasser."];
		var Family_Status1 = ["Aristocratie: Vous avez grandi dans un noble manoir avec des serviteurs pour vous attendre, mais vous vous attendiez toujours à vous comporter et à impressionner.","Adopté par un mage: Vous avez été donné à un mage à un jeune âge. Vous viviez dans le confort mais voyiez à peine votre concierge, toujours occupé.","Chevaliers: Vous avez grandi dans un manoir où vous avez appris à être une vraie dame ou un seigneur. Votre destin a été fixé dès la naissance.","Famille de marchands: vous avez grandi parmi les marchands et vous avez toujours été entouré de cris, de marchandages et d'argent.","Famille d'artisans: vous avez grandi dans un atelier d'artisans. Vos journées ont été remplies des bruits incessants de la création, et souvent longues.","Entertainer Family: Vous avez grandi avec un groupe d'artistes. Vous avez peut-être voyagé ou joué dans un théâtre.","Famille paysanne: vous avez grandi dans une ferme à la campagne. Vous n'aviez pas grand-chose, votre vie était simple mais dangereuse."];
		var Family_Status2 = ["Aristocratie: Vous avez grandi dans un manoir, vous vous entraînez à bien connaître le monde de la cour. Le luxe n'était que votre motivation.","Haut clergé: vous avez été élevé parmi le clergé du Grand Soleil. Vous avez grandi pieux et toujours conscient que l'Église vous guiderait.","Chevaliers: Vous avez grandi en sachant que votre devoir était envers l'empereur et que tout votre luxe était une récompense pour votre service éventuel.","Famille d'artisan: Vous avez grandi dans une boutique d'artisan, apprenant à créer des produits à vendre dans le monde entier. Vous avez appris la valeur de la qualité.","Famille de marchands: vous avez grandi en vendant des produits dans tout l'Empire. Vous avez vu toutes sortes de produits exotiques du monde entier.","Né dans la servitude: vous êtes né dans la servitude et avez vécu dans des quartiers simples. Vous possédiez très peu et peiniez souvent.","Famille paysanne: Vous avez grandi dans l'une des milliers de fermes de l'Empire. Vous aviez peu de choses à votre nom mais la vie était simple."];
		var Family_Status3 = ["Aristocratie: Vous avez grandi dans un palais et vous avez constamment rappelé la gloire du passé. Vous deviez être à la hauteur de l'héritage.","Guerrier noble: Vous avez grandi en tant qu'enfant de noble guerrier, censé élever la réputation de votre famille et ne jamais déshonorer votre héritage.","Marchands: vous avez grandi parmi les marchands itinérants. La vie était parfois difficile, mais les loisirs non humains ont toujours de la valeur.","Famille de scribes: Vous avez grandi en tant qu'enfant de scribes, enregistrant et protégeant le plus possible l'histoire des personnes âgées.","Artistes: Vous avez grandi en chantant des chansons et en jouant des pièces. Vous avez travaillé dans les coulisses, aidé à écrire des chansons et réparé des instruments.","Famille d'artisans: Vous avez grandi dans une famille d'artisans, visitant d'anciens palais pour vous inspirer et passant des heures chaque jour sur des projets.","Famille de roturiers: vous avez grandi dans une famille basse-née, occupée aux manoirs des autres ou occupant de petits emplois dans votre ville natale."];
		var Clothing = ["Un uniforme", "Vêtements de voyage", "Vêtements fantaisie", "Vêtements déchiquetés", "Vêtements utilitaires", "Vêtements traditionnels", "Décolleté", "Vêtements lourds", "Vêtements étranges", " Vêtements flamboyants "];
		var Personality = ["secret", "rebelle", "violent", "idéaliste", "contemplatif", "sévère", "trompeur", "amical", "arrogant", "nerveux"];
		var Hair = ["long et lâche","court court","coupe courte","tressé","long et sauvage","chauve","uniformément court","en lambeaux et en désordre","coiffure compliquée","côtés rasés",];
		var Affectations = ["Trophées", "Bagues et bijoux", "Bibelots", "Tatouages", "Peinture de guerre", "Cape ombragée", "Bandanas brillants", "Cache-oeil", "Fourrures", "Insignes et plaques"];
		var Valued_Person = ["Un parent","Un frère","Un amoureux","Un ami","Toi même","Un animal de compagnie","Un mentor","Une personnalité publique","Un héros personnel","Personne"];
		var Valued = ["Argent","Honneur","Votre parole","Hédonistique","Connaissance","Vengeance","Puissance","L'amour","Survie","Relation amicale"];
		var Feelings = ["Les gens sont des outils à utiliser","Notre espèce est supérieure aux autres","On ne peut jamais faire confiance aux gens","Les gens doivent faire leurs preuves","Neutre","Neutre","Les gens sont super","Tout le monde mérite de mourir","Les gens sont des porcs hédonistes","Toute vie est précieuse"];
	}
	
	var Rand1 = Math.floor(Math.random() * Math.floor(10));	// Région
	var Rand2 = Math.floor(Math.random() * Math.floor(10));	// Nilfgaardian Origin
	var Rand3 = Math.floor(Math.random() * Math.floor(10));	// Origin
	var Rand4 = Math.floor(Math.random() * Math.floor(10));	// Family
	var Rand5 = Math.floor(Math.random() * Math.floor(10));	// Parents
	var Rand6 = Math.floor(Math.random() * Math.floor(10));	// Lifepath ...
	var Rand7 = Math.floor(Math.random() * Math.floor(10));	// Clothing
	var Rand8 = Math.floor(Math.random() * Math.floor(10));	// Personality
	var Rand9 = Math.floor(Math.random() * Math.floor(10));	// Hair
	var Rand10 = Math.floor(Math.random() * Math.floor(10));// Affectations
	var Rand11 = Math.floor(Math.random() * Math.floor(10));// Valued_Person
	var Rand12 = Math.floor(Math.random() * Math.floor(10));// Valued
	var Rand13 = Math.floor(Math.random() * Math.floor(10));// Feelings
	
	if(Rand1%2 == 0){var El1 = Region[1];var TypOrigine = 2;if(Rand2 < 3){var El3 = NOrigin[10];}else{var El3 = NOrigin[Rand3];}
	}else{var El1 = Region[0];var TypOrigine = 1;var El3 = NKOrigin[Rand3];}
	if(Rand1 > 7){var El1 = Region[2];var TypOrigine = 3;if(Rand3%2 == 0){var El3 = EOrigin[0];}else{var El3 = EOrigin[1];}}
	
	if(TypOrigine == 1){if(Rand4%2 == 0){if(Rand5%2 == 0){
		if(Rand6 > 4){var El6 = Family_Status1[6];}else if(Rand6 > 6){var El6 = Family_Status1[Rand6];}else{var El6 = Family_Status1[Rand6];}
		}else{var El6 = Parental_Fate1[Rand6];}}else{var El6 = Family_Fate1[Rand6];}}
	if(TypOrigine == 2){if(Rand4%2 == 0){if(Rand5%2 == 0){
		if(Rand6 > 4){var El6 = Family_Status2[6];}else if(Rand6 > 6){var El6 = Family_Status2[Rand6];}else{var El6 = Family_Status2[Rand6];}
		}else{var El6 = Parental_Fate2[Rand6];}}else{var El6 = Family_Fate2[Rand6];}}
	if(TypOrigine == 3){if(Rand4%2 == 0){if(Rand5%2 == 0){
		if(Rand6 > 4){var El6 = Family_Status3[6];}else if(Rand6 > 6){var El6 = Family_Status3[Rand6];}else{var El6 = Family_Status3[Rand6];}
		}else{var El6 = Parental_Fate3[Rand6];}}else{var El6 = Family_Fate3[Rand6];}}

	var El7 = Clothing[Rand7];
	var El8 = Personality[Rand8];
	var El9 = Hair[Rand9];
	var El10 = Affectations[Rand10];
	var El11 = Valued_Person[Rand11];
	var El12 = Valued[Rand12];
	var El13 = Feelings[Rand13];

    if(langue == "1"){       
		document.getElementById('résultat_aff4').innerHTML = "Origine: "+El3+" ("+El1+")<br>Lifepath: "+El6+"<br>Style :<br><div style='margin-left:50px;'>Clothing: "+El7+"<br>Personality: "+El8+"<br>Hair: "+El9+"<br>Affectations: "+El10+"</div><br>Values :<br><div style='margin-left:50px;'>Valued Person: "+El11+"<br>Value: "+El12+"<br>Feelings on People: "+El13+"</div>";
	}else{
		document.getElementById('résultat_aff4').innerHTML = "Origine: "+El3+" ("+El1+")<br>Passé: "+El6+"<br>Style :<br><div style='margin-left:50px;'>Vêtements: "+El7+"<br>Personnalité: "+El8+"<br>Cheveux: "+El9+"<br>Particularité: "+El10+"</div><br>Valeurs :<br><div style='margin-left:50px;'>Personne valorisée: "+El11+"<br>Valeur: "+El12+"<br>Sentiments sur les gens: "+El13+"</div>";
	}	
}

function WitcherGen(){
	var langue = document.getElementById('langue_choisi').value;
	if(langue == "1"){
		var Age = ["Infancy : You were taken to become a witcher when you were a toddler, between 1 and 2 years old. You have no memories of life before becoming a witcher and had nothing to cling to when taking the Trial of the Grasses.","Early Childhood : You were taken to become a witcher when you were young, between 4 and 6 years old. You had some normal memories to aid you when taking the Trial of the Grasses.","Late Childhood : You were taken to become a witcher when you were relatively old, between 8 and 11 years old. While training was somewhat harder, your many memories bolstered you when you took the Trial of the Grasses."];
		var School = ["The Wolf School : You trained at Kaer Morhen in the heights of the Blue Mountains. Your training was tough and structured, focusing on a very rounded approach to the Witcher profession. You were taught to strike hard and fast to end hunts quickly.","The Gryphon School : You were trained at Kaer Y Seren along the coastal side of the Dragon Mountains. Your training was heavily focused on fighting any number of opponents and using your limited magical power to its greatest potential.","The Cat School : You trained in the Dyn Marv Caravan, a traveling troop of witchers who sold their skills to anyone who could pay, for any job. Their mutations and training flayed your emotions, and you struggle against violent, cruel impulses.","The Viper School : You trained at Gorthwr Gvaed in the deep chasms of the Tir Tochair Mountains. Unlike other witchers, you were trained on twin blades and an assassination-based approach to killing monsters.","The Bear School : You trained in the snowy heights of the Amell Mountains at Haern Cadvch. You conditioned your body to endure all manner of punishment and move quickly and efficiently in heavy steel armor."];
		var Training = ["Wounded on the Gauntlet : You were wounded while running the gauntlet around your School. Your leg was broken badly, and even after healing it is still slightly stiff.","Stolen Knowledge : While training at your School you snuck into the libraries of the keep and copied one of the secret witcher diagrams, smuggling the information out with you.","Made a Rival : While training at the keep you formed a rivalry with another witcher in training. Even after mutations, their hatred of you continues to boil.","Easy Mutations : You adapted well to the lesser mutations and mutagenic mushrooms you were fed early in training. When the time came for the Trial of the Grasses, you were well prepared.","Magical Backfire : A failure casting a sign caused minor damage to your body. It was horrifically painful, and even after your body healed your Vigor threshold was lowered.","Top of Your Class : You were one of the best swordsmen in your class and your skills haven’t dulled. You perform the complex movements, pirouettes, and spins of the witcher with ease.","Bad Reaction to Mutagens You had allergic reactions to the mutagenic mushrooms and chemical compounds given to you in early training. When the Trial of the Grasses came, it was more difficult.","Made a Friend : You made a fast friend in your early years of witcher training. The rough training and dangerous situations sealed your bond.","Wounded by the Pendulum : You were wounded while training on the pendulum. You fell from the posts and broke several bones on the rocks below. While healed, you are a little stiffer than before.","Extensive Research : While sword training was important, you spent most of your free time in the libraries of the keep studying the monsters of the world and taking notes."];
		var Trials = ["Nearly Fatal : The Trial of the Grasses nearly destroyed your body. Though you survived the process, your body and mind were damaged permanently.","Poorly Accepted : The Trial of the Grasses went poorly and the witchers in charge of mutation weren’t entirely sure you would make it. You survived, but not without mental scars.","Passable Mutations : The Trial of the Grasses went well. You passed into the ranks of witchers with nothing more than memories of horrible pain.","Extra Mutations : Your body was very receptive to the Trial of the Grasses and you had extra mutations applied to you. Your body handled it well, and all of the pain paid off in the end."];
		var Event = ["Given a Child by the Law of Surprises : Along your travels you invoked the Law of Surprises and received a child. They may have been a boy, in which case they were made into a witcher, or a girl, in which case their fate was up to you.","Hunted by a Sentient Monster : The tables turned during one of your hunts. Sentient monsters like grave hags and katakan can be dangerous quarry, and you wound up becoming the hunted for a stressful night.","Fought Alongside a Knight : You did battle alongside a noble knight. This may have been against both of your wishes or even an accident, but fighting beside a noble changed your outlook on knights and your job as a witcher.","Captured by a Mage for Testing : Mages lust after the secrets of Witcher mutations. At some point in your life, you were captured by a mage who experimented on you in an attempt to reverse-engineer them.","Worked for a Nobleman : For a time you worked for a nobleman. The pay was good, but it was strange and aggravating to have to hide most of your actions to avoid shaming the family by bringing their secrets to light.","Went Beyond the Boundaries : Once, you traveled beyond the borders of the Continent—past the Dragon Mountains, the Tir Tochair or Blue Mountains, or the Great Sea. You have seen far lands unknown to most others.","Meaningful Romance : Most witchers remain neutral and avoid meaningful relationships. However, this didn’t stop you. You fell in love and actually considered settling down. It still occurs to you sometimes.","Fought for your Keep : You fought at a siege of your keep. You were outnumbered and overpowered, but you stayed nonetheless. You survived the siege with serious wounds, but saw your brethren dying around you.","Gained Infamy : After helping a city with a monster, the people became afraid and turned on you. They might have even tried to kill you. Either way, you’ve seen what kind of reward you can expect from people.","Gained Fame : You were well-received in a town after helping them with a monster. You didn’t expect free drinks or women casting you glances, but that’s what you got. You haven’t seen such kindness again, but it was heartening."];
		var Now = ["Became a Personal Witcher : You signed on to work for a merchant group, noble house, or important person as a personal witcher. You work for modest pay and hunt what they tell you to hunt. Mostly it’s monsters...","Looking For Work : The hard life of a witcher continues. You spend a lot of time on the road, lamenting the efficiency of your kind and the extinction of monsters. You travel constantly and never settle down.","Became a Hermit : You gave up on the life of a witcher and traveled out into the wilderness. Now you live as a hermit in the wilds. Only now that monsters are returning have you started to venture out again.","Turned to a Normal Life : You’ve tried for decades to leave the witcher life behind. It’s difficult, since people won’t ever really accept you, but you have managed to cobble together an almost normal life. Good luck.","Became a Dangerous Criminal : Eventually all the negativity and thankless people got to you— you decided that with fewer and fewer monsters, it was time to start hunting people. You can determine what you do to survive."];
	}else{
		var Age = ["Petite enfance: vous avez été amené à devenir un sorceleur quand vous étiez enfant, entre 1 et 2 ans. Vous n'avez aucun souvenir de la vie avant de devenir un sorceleur et n'aviez rien à quoi vous accrocher lorsque vous participiez à l'Épreuve des herbes . "," Petite enfance: vous avez été emmené pour devenir sorceleur quand vous étiez jeune, entre 4 et 6 ans. Vous aviez des souvenirs normaux pour vous aider lors de l'essai des herbes. "," Enfance tardive: vous étiez pris pour devenir un sorceleur quand vous étiez relativement vieux, entre 8 et 11 ans. Alors que l'entraînement était un peu plus difficile, vos nombreux souvenirs vous ont soutenu lorsque vous avez participé à l'épreuve des herbes."];		var School = [];
		var School = ["L'école du Loup: Vous vous êtes entraîné à Kaer Morhen dans les hauteurs des Blue Mountains. Votre formation a été difficile et structurée, axée sur une approche très complète du métier de sorceleur. On vous a appris à frapper fort et vite pour terminer chasse rapidement. "," L'école du Griffon Vous avez été formé à Kaer Y Seren le long de la côte des montagnes du Dragon. Votre formation était fortement axée sur la lutte contre un certain nombre d'adversaires et l'utilisation de votre pouvoir magique limité à son plus grand potentiel. ", "L'école du Chat: Vous vous êtes entraîné dans la caravane Dyn Marv, une troupe itinérante de sorciers qui a vendu ses compétences à quiconque pouvait payer, pour n'importe quel travail. Leurs mutations et leur formation ont effrayé vos émotions, et vous luttez contre des impulsions violentes et cruelles." , "L'école de la Vipère: Vous vous êtes entraîné à Gorthwr Gvaed dans les abîmes profonds des montagnes de Tir Tochair. Contrairement à d'autres sorceleurs, vous avez été formé sur les lames jumelles et une approche basée sur l'assassinat pour tuer des monstres.", "L'école de l'Ours: Vous vous êtes entraîné dans le sn hauteurs des montagnes Amell à Haern Cadvch. Vous avez conditionné votre corps à supporter toutes sortes de punitions et à vous déplacer rapidement et efficacement dans une lourde armure d'acier. "];
		var Training = ["Blessé au gantelet: vous avez été blessé lors de l'exécution du gantelet autour de votre école. Votre jambe a été gravement cassée, et même après la guérison, elle est encore légèrement raide.", "Connaissances volées: pendant l'entraînement à votre école, vous vous êtes faufilé dans les bibliothèques du donjon et copié l'un des diagrammes de sorceleur secret, en faisant passer les informations avec vous. "," Made a Rival: Pendant l'entraînement au donjon, vous avez formé une rivalité avec un autre sorceleur en formation. Même après les mutations, leur haine de vous continue à bouillir. "," Mutations faciles: Vous vous êtes bien adapté aux petites mutations et aux champignons mutagènes que vous avez été nourris au début de la formation. Lorsque le moment est venu pour L'Epreuve des Herbes, vous étiez bien préparé. "," Magical Backfire : Un échec à lancer un signe a causé des dommages mineurs à votre corps. C'était horriblement douloureux, et même après que votre corps ait guéri, votre seuil de vigueur a été abaissé. "," Top of Your Class: Vous étiez l'un des meilleurs épéistes de votre classe et de votre compétences ne se sont pas émoussées. rm les mouvements complexes, les pirouettes et les tours de sorceleur avec facilité. "," Mauvaise réaction aux mutagènes Vous avez eu des réactions allergiques aux champignons mutagènes et aux composés chimiques qui vous ont été donnés au début de la formation. Lorsque le procès des herbes est arrivé, c'était plus difficile. L'entraînement difficile et les situations dangereuses ont scellé votre lien. "," Blessé par le pendule: Vous avez été blessé pendant l'entraînement au pendule. Vous êtes tombé des poteaux et avez cassé plusieurs os sur les rochers en dessous. Pendant que vous êtes guéri, vous êtes un peu plus raide qu'auparavant. "," Recherche approfondie: Bien que l'entraînement à l'épée était important, vous avez passé la plupart de votre temps libre dans les bibliothèques du donjon à étudier les monstres du monde et à prendre des notes. "];
		var Trials = ["Presque fatal: L'Epreuve des Herbes a presque détruit votre corps. Bien que vous ayez survécu au processus, votre corps et votre esprit ont été endommagés de façon permanente.", "Mal accepté: L'Epreuve des Herbes s'est mal passé et les sorciers en charge de mutation n'étaient pas tout à fait sûrs que vous y arriveriez. Vous avez survécu, mais pas sans cicatrices mentales. "," Mutations passables: Le procès des herbes s'est bien passé. Vous êtes passé dans les rangs des sorciers avec rien de plus que des souvenirs d'horribles douleurs . "," Mutations supplémentaires: votre corps a été très réceptif au procès des herbes et vous avez subi des mutations supplémentaires. Votre corps l'a bien géré, et toute la douleur a finalement payé. "];
		var Event = ["Donné à un enfant par le Droit de Surprise: Au cours de vos voyages, vous avez invoqué la Droit de Surprise et reçu un enfant. Il peut s'agir d'un garçon, auquel cas il a été transformé en sorceleur ou en fille en auquel cas leur sort dépendait de vous. "," Chassé par un monstre sensible: Les tables se sont retournées lors de l'une de vos chasses. Les monstres sensibles comme les sorcières et les katakan peuvent être une carrière dangereuse, et vous vous retrouvez devenir le chassé pour une nuit stressante . "," Combattu aux côtés d'un chevalier: Vous avez combattu aux côtés d'un noble chevalier. Cela a peut-être été contraire à vos souhaits ou même à un accident, mais combattre aux côtés d'un noble a changé votre vision des chevaliers et de votre travail de sorceleur. ", "Capturés par un mage pour les tester: les mages convoitent les secrets des mutations de Witcher. À un moment donné de votre vie, vous avez été capturé par un mage qui a fait des expériences sur vous pour tenter de les désosser.", "Travaillé pour un noble : Pendant un certain temps, vous avez travaillé pour un noble. Le salaire était bon, mais c'était étrange et aggra vating d'avoir à cacher la plupart de vos actions pour éviter de faire honte à la famille en dévoilant leurs secrets. "," Went Beyond the Boundaries: Once, you voyagé au-delà des frontières du continent - au-delà des montagnes du Dragon, du Tir Tochair ou Blue Les montagnes ou la Grande Mer. Vous avez vu des terres lointaines inconnues de la plupart des autres. "," Romance significative: La plupart des sorciers restent neutres et évitent les relations significatives. Mais cela ne vous a pas arrêté. Vous êtes tombé amoureux et avez envisagé de vous installer. Cela vous vient parfois à l'esprit. "," Combattu pour votre donjon: Vous avez combattu lors d'un siège de votre donjon. Vous étiez en infériorité numérique et maîtrisé, mais vous êtes néanmoins resté. Vous avez survécu au siège avec de graves blessures, mais avez vu vos frères mourir autour de vous. "," Gained Infamy: Après avoir aidé une ville avec un monstre, les gens ont eu peur et se sont tournés contre vous. Ils ont peut-être même essayé de vous tuer. Quoi qu'il en soit, vous avez vu le genre de récompense que vous pouvez attendre des gens. "," Acquis la renommée: vous avez été bien reçu dans une ville après les avoir aidés avec un monstre. Vous ne vous attendiez pas à des boissons gratuites ou à des femmes qui vous jettent des regards, mais c'est ce que vous avez. Vous n’avez pas revu une telle gentillesse, mais c’était réconfortant. "];
		var Now = ["Est devenu un sorceleur personnel: vous vous êtes inscrit pour travailler pour un groupe de marchands, une maison noble ou une personne importante en tant que sorceleur personnel. . "," Recherche d'emploi: la dure vie d'un sorceleur continue. Vous passez beaucoup de temps sur la route, déplorant l'efficacité de votre espèce et l'extinction des monstres. Vous voyagez constamment et ne vous installez jamais. "," Est devenu un ermite: Vous avez abandonné la vie d'un sorceleur et vous êtes parti dans le désert. Maintenant, vous vivez comme un ermite dans la nature. Ce n'est que maintenant que les monstres reviennent que vous avez recommencé à vous aventurer. "," Passé à la normale La vie: Vous avez essayé pendant des décennies de laisser la vie de sorceleur derrière vous. C'est difficile, car les gens ne vous accepteront jamais vraiment, mais vous avez réussi à bricoler une vie presque normale. Bonne chance. "," Est devenu un criminel dangereux : Finalement, toute la négativité et les gens ingrats vous ont touché - vous avez décidé qu'avec de moins en moins de monstres, il était temps de commencer à chasser les gens. Vous pouvez déterminer ce que vous faites pour survivre. "];
	}

	var Rand1 = Math.floor(Math.random() * Math.floor(10));	// Age
	var Rand2 = Math.floor(Math.random() * Math.floor(5));	// School
	var Rand3 = Math.floor(Math.random() * Math.floor(10));	// Training
	var Rand4 = Math.floor(Math.random() * Math.floor(10));	// Trials
	var Rand5 = Math.floor(Math.random() * Math.floor(10));	// Event
	var Rand6 = Math.floor(Math.random() * Math.floor(10));	// Now

	if(Rand1 < 2){var El1 = Age[0];}else if(Rand1 > 7){var El1 = Age[2];}else{var El1 = Age[1];}
	var El2 = School[Rand2];
	var El3 = Training[Rand3];
	if(Rand4 == 0){var El4 = Trials[0];}else if(Rand4 == 9){var El4 = Trials[3];}else if(Rand4 < 3){var El4 = Trials[1];}else{var El4 = Trials[2];}
	var El5 = Event[Rand5];
	if(Rand6 == 9){var El6 = Now[4];}else if(Rand6 == 8){var El6 = Now[3];}else if(Rand6 > 1){var El6 = Now[2];}else{var El6 = Now[Rand6];}
	
    if(langue == "1"){       
		document.getElementById('résultat_aff5').innerHTML = "<b>When Did You Become A Witcher?</b> "+El1+"<br><b>School:</b> "+El2+"<br><b>Early Training Event:</b> "+El3+"<br><b>Outcome of the Trials:</b> "+El4+"<br><b>Most Important Event:</b> "+El5+"<br><b>Where You Are Now:</b> "+El6;
	}else{
		document.getElementById('résultat_aff5').innerHTML = "<b>Quand est-il devenu un Witcher?</b> "+El1+"<br><b>Ecole:</b> "+El2+"<br><b>Entrainement:</b> "+El3+"<br><b>Epreuve:</b> "+El4+"<br><b>Evenement le plus important:</b> "+El5+"<br><b>Qui est-il maintenant:</b> "+El6;
	}
}

function BasicGen(){
	var langue = document.getElementById('langue_choisi').value;
	if(langue == "1"){
		var Race = ['Human','Aen Seidhe','Dwarf'];
		var Gender = ['Female','Male'];
		var Age = ['Child','Teen','Young adult','Adult','Elder'];
		var Personality = ["Shy","Rebellious","Arrogant","Headstrong","Friendly","Secretive","Nervous","Flirtatious","Eccentric","Aloof"];
		var History = ["Lost everything","Family was killed","Fought in the Northern War","Thinks they have magic","Almost died","Saved by a witcher","Used to be a priest","Once ruled a small town","Lived as a bandit","Killed a dangerous monster"];
		var Standing = ["Slave ","Slave ","Poor","Poor ","Poor ","Average ","Well to do ","Well to do ","Rich  ","Nobility"];
		var Romance = ["None","None","None","Uninterested in love","Debauchery ","Playboy ","Interested in a player ","A dedicated lover ","Married ","Star-crossed lovers"];
		var Secret = ["Is secretly a mage","Found a lost treasure","Is a wanted criminal","Is a secret service agent","Has a secret life","Has a Secret Profession","Is a cross-dresser","Is a deserter","Has a secret lover","Has a hex or curse of your choice"];
	}else{
		var Race = ['Humain','Aen Seidhe','Nain'];
		var Gender = ['Femme','Homme'];
		var Age = ['Enfant','Adoslescent','Jeune adulte','Adulte','Ancien'];
		var Personality = ["Timide","Rebelle","Arrogant","Têtu","Amical","Secret","Nerveux","Coquette","Excentrique","Distant"];
		var History = ["A tout perdu","Sa famille a été tuée","A combattu pendant la guerre du Nord","Pense qu'il a de la magie","Presque mort","A été sauvé par un sorceleur","A été prêtre","A gouverné une petite ville","A vécu comme un bandit","A tué un monstre dangereux"];
		var Standing = ["Esclave","Esclave","Pauvre","Pauvre","Pauvre","Moyenne","Aisé","Aisé","Riche","Noble"];
		var Romance = ["Aucune","Aucune","Aucune","Pas intéressé par l'amour","Débauche","Playboy","Intéressé par un joueur","Un amoureux dédié","Marié","Amants maudits"];
		var Secret = ["Est secrètement un mage","A trouvé un trésor perdu","Est un criminel recherché","Est un agent des services secrets","A une vie secrète","A une profession secrète","Est un travesti","Est un déserteur","A un amant secret","A une malédiction de votre choix"];
		}

	var Rand1 = Math.floor(Math.random() * Math.floor(10));	// Race
	var Rand2 = Math.floor(Math.random() * Math.floor(10));	// Gender
	var Rand3 = Math.floor(Math.random() * Math.floor(5));	// Age
	var Rand4 = Math.floor(Math.random() * Math.floor(10));	// Personality
	var Rand5 = Math.floor(Math.random() * Math.floor(10));	// History
	var Rand6 = Math.floor(Math.random() * Math.floor(10));	// Standing	
	var Rand7 = Math.floor(Math.random() * Math.floor(10));	// Romance	
	var Rand8 = Math.floor(Math.random() * Math.floor(10));	// Secret	

	if(Rand1 < 4){var El1 = Race[0];}else if(Rand1 > 6){var El1 = Race[2];}else{var El1 = Race[1];}
	if(Rand2%2 == 0){var El2 = Gender[0];}else{var El2 = Gender[1];}
	var El3 = Age[Rand3];
	var El4 = Personality[Rand4];
	var El5 = History[Rand5];
	var El6 = Standing[Rand6];
	var El7 = Romance[Rand7];
	var El8 = Secret[Rand8];
	
    if(langue == "1"){       
		document.getElementById('résultat_aff6').innerHTML = "<b>Basic NPC :</b> Race: "+El1+". Gender: "+El2+". Age: "+El3+". Personality: "+El4+"<br><b>Background :</b> "+El5+". Standing: "+El6+". Romance: "+El7+". Secret: "+El8;
	}else{
		document.getElementById('résultat_aff6').innerHTML = "<b>PNJ basique :</b> Race: "+El1+". Sexe: "+El2+". Age: "+El3+". Personnalité: "+El4+"<br><b>Histoire :</b> "+El5+". Classe sociale: "+El6+". Romance: "+El7+". Secret: "+El8;
	}
}