	function InnGen(){
    	var langue = document.getElementById('langue_choisi').value;
        if(langue == "1"){
          var Establishment = ['Hostel','Inn','Tavern','Brothel','Boarding House','Casino','Hotel','Guest Room'];
          var Comfort = ['Squalid (1 SP)','Poor (2 SP)','Modest (5 SP)','Respectable (1 GP)','Comfortable (2 GP)','Wealthy (4 GP)','Lavish (6 GP)','Royal (10 GP)'];
          var Innkeeper = ['Dwarf','Human/Half-Elf','Tiefling','Gnome','Half-Orc','Dragonborn','Elf','Halfling'];
          var Personality = ['Old, cranky, and not fond of visitors','Nervous, as if they’re hiding something','Loud and boisterous: the life of every party','Obsessed with cleanliness and hates even the sight of mud','Just trying to get to the end of their shift','Always drunk, regardless of the time of day','Knows Common perfectly well, but refuses to speak it','Exceedingly competent and professional'];
          var Feature = ["A massive portrait of the innkeeper’s father hangs behind the front desk. The eyes follow you wherever you go.","There’s an entrance to an underground cavern system hidden in the basement.","There are messages in Thief’s Cant written under some of the beds directing the reader to nearby dead-drops for loot.","A ghost wanders the halls at night, and occasionally during the day as well.","One of the rooms is always locked. The actual owner is kept tied up inside at all times.","A local crime boss has made this establishment their base of operations against the wishes of the owner and the staff.","There’s a mimic loose somewhere in the establishment, but the owner isn’t quite sure where.","Meals are disproportionately cheap, but the meat doesn’t taste like anything the party has ever eaten before."];
		  var Comfort2 = ["You’re sleeping on a pile of hay in the stables, and your bathroom is a bucket, but at least you’re out of the rain.","Just because you can run an inn doesn’t mean that you should. These places always have something about them that makes the experience unpleasant, like overflowing chamber pots or a rat infestation. You do technically have a bed, but you may be sharing it with one or more people.","The accommodation level for the average village inn. Well-kept, but unfussy. The mattresses are still stuffed with straw, and the blankets are scratchy, but everything is clean, and you don’t have to worry about vermin.","","Once you get into slightly larger towns, you’ll start to find places that cater to the traveling merchant class. There are occasional feather beds, softer pillows, and meals that can be brought to your room. It isn’t exactly fancy, but it’s certainly a step above average.","This is when you get your own private bathroom. These are often the nicest accommodations that you can find in small cities. They can feel a little bit pretentious and stuffy at times, but it doesn’t make the mattresses any less comfortable.","The favorite accommodation level of rich merchants and petty aristocrats. It’s roughly equivalent to the level of most boutique luxury hotels. The thread counts are high, everything is stuffed with goose down, and service is always quick. Forget a private bathroom; in places like this, you have your own bath tub.","Equivalent to the presidential suite at a five-star hotel. There are multiple rooms, dedicated serving staff, and as much alcohol as you can drink. This level of accommodation can only be found in large cities, and cater to an elite clientele. If your party isn’t well-dressed, they may not be allowed inside no matter how much money they can wave around."];
        }
        else{
          var Establishment = ['Auberge de jeunesse', 'Auberge', 'Taverne', 'Bordel', 'Pension de famille', 'Casino', 'Hôtel', "Chambre d'hôtes"];
          var Comfort = ['Misérable (1 SP)','Pauvre (2 SP)','Modeste (5 SP)','Respectable (1 GP)','Confortable (2 GP)','Riche (4 GP)','Somptueux (6 GP)','Royal (10 GP)'];
          var Innkeeper = ['Nain','Human/Demi-Elf','Tieflin','Gnome','Demi-Orc','Dragonborn','Elfe','Halflin'];
          var Personality = ["Vieux, grincheux et n'aimant pas les visiteurs", "Nerveux, comme s'ils cachaient quelque chose", "Bruyant et agité: la vie de chaque fête", "Obsédé par la propreté et déteste même la vue de la boue", "Essaie juste de finir sa journée de travail", "Toujours ivre, quelle que soit l'heure de la journée","Connaît parfaitement le commun, mais refuse de le parler","Extrêmement compétent et professionnel"];
          var Feature = ["Un portrait massif du père de l'aubergiste est accroché derrière la réception. Les yeux vous suivent partout où vous allez.", "Il y a une entrée dans un système de cavernes souterraines caché dans le sous-sol.", "Il y a des messages écrits en argot de voleur sous certains des lits qui dirige le lecteur vers des tombes mortes à proximité pour récupérer le butin. "," Un fantôme se promène dans les couloirs la nuit, et parfois aussi pendant la journée. "," Une des chambres est toujours fermée. Le propriétaire actuel est attaché à l'intérieur. "," Un patron du crime local a fait de cet établissement leur base d'opérations contre la volonté du propriétaire et du personnel. "," Il y a un mimétisme quelque part dans l'établissement, mais le propriétaire n'est pas tout à fait sûr où. "," Les repas sont disproportionnellement bon marché, mais la viande n'a pas le même goût de tout ce que le groupe a jamais mangé auparavant. "];
		  var Comfort2 = ["Vous dormez sur un tas de foin dans les étables, et votre salle de bain est un seau, mais au moins vous êtes à l'abri de la pluie.", "Ce n'est pas parce que vous pouvez gérer une auberge que vous devriez. Ces endroits ont toujours quelque chose à leur sujet qui rend l'expérience désagréable, comme des pots de chambre débordants ou une infestation de rats. Vous avez techniquement un lit, mais vous pouvez le partager avec une ou plusieurs personnes. "," La qualité de l'herbergement pour cette auberge de village est moyenne. Bien entretenu, mais sans prétention. Les matelas sont encore bourrés de paille et les couvertures sont éraflées, mais tout est propre et vous n'avez pas à vous soucier de la vermine. "," "," Une fois que vous arrivez dans des villes un peu plus grandes, vous commencez à trouver des endroits adaptés à la classe des marchands ambulants. Il y a parfois des lits en plumes, des oreillers plus moelleux et des repas qui peuvent être apportés dans votre chambre. c'est certainement un cran au-dessus de la moyenne. "," C'est alors que vous avez votre propre salle de bain privée. Ce sont souvent les plus beaux hébergements que vous pouvez trouver dans les petites villes. Ils peuvent parfois se sentir un peu prétentieux et étouffants, mais cela ne rend pas les matelas moins confortables. "," Le niveau d'hébergement préféré des riches marchands et des petits aristocrates. Il est à peu près équivalent au niveau de la plupart des hôtels de luxe de charme. Le nombre de fils est élevé, tout est bourré de duvet d'oie et le service est toujours rapide. Oubliez une salle de bain privée; dans des endroits comme celui-ci, vous avez votre propre baignoire. "," Equivalent à la suite présidentielle d'un hôtel cinq étoiles. Il y a plusieurs salles, un personnel de service dévoué et autant d'alcool que vous pouvez en boire. Ce niveau d'hébergement ne peut être trouvé que dans les grandes villes et s'adresse à une clientèle d'élite. Si votre groupe n'est pas bien habillé, il se peut qu'ils ne soient pas autorisés à l'intérieur, peu importe le montant d'argent qu'ils peuvent faire circuler. "];
        }
        var Rand1 = Math.floor(Math.random() * Math.floor(8));
        var Rand2 = Math.floor(Math.random() * Math.floor(8));
        var Rand3 = Math.floor(Math.random() * Math.floor(8));
        var Rand4 = Math.floor(Math.random() * Math.floor(8));
        var Rand5 = Math.floor(Math.random() * Math.floor(8));
        var El1 = Establishment[Rand1];
        var El2 = Comfort[Rand2];var El2_2 = Comfort2[Rand2];
        var El3 = Innkeeper[Rand3];
        var El4 = Personality[Rand4];
        var El5 = Feature[Rand5];
		
		
        if(langue == "1"){       
			document.getElementById('résultat_aff').innerHTML = "Establishment: "+El1+"<br>Comfort: "+El2+". "+El2_2+"<br>Innkeeper: "+El3+". "+El4+".<br>Feature: "+El5;
		}
		else{
			document.getElementById('résultat_aff').innerHTML = "Etablissement: "+El1+"<br>Confort: "+El2+". "+El2_2+"<br>Barman: "+El3+". "+El4+".<br>Particularité: "+El5;
		}
    }
