var Rencontre = {
	"Humain": [
		{
		  "Nom": "ARCHERS SCOIA’TAEL",
		  "Menace": "Faible Complexe",
		  "Récompense": "20 couronnes",
		  "Armure": "5",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Forêts","Ville"],
		  "Intelligence": "Humaine",
		  "Organisation": "Commandos de 3 à 15 individus",
		  "Note": "Les archers Scoia’tael commencent d’abord par décocher des flèches normales pour tenter de tuer toutes leurs cibles rapidement. Ils réservent leurs fouisseuses elfes pour les ennemis qu’ils abhorrent de tout leur cœur et les fuyards qu’ils devront traquer après la bataille."
		},
		{
		  "Nom": "BANDITS",
		  "Menace": "Faible Simple",
		  "Récompense": "10 couronnes",
		  "Armure": "5",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Ville","Route"],
		  "Intelligence": "Humaine",
		  "Organisation": "Bandes de 3 à 15 individus",
		  "Note": "Le niveau de compétences des bandits est extrêmement variable. Le profil présenté ici est celui d’un voyou de base, le genre de gros bras qui surveille l’entrepôt d’un criminel ou tend des embuscades aux voyageurs sur les routes. Vous pouvez tout à fait modifier les caractéristiques des bandits pour les rendre plus ou moins menaçants. Pour représenter un paysan ordinaire ou un scélérat de bas étage, diminuez ses RÉF et sa DEX à 3, et ses PS à 15. Sachez toutefois que ces brigands ne représenteront pas un défi pour les personnages combattants. Si vous voulez peupler les routes de voyous endurcis, augmentez leur RÉF et de DEX à 7 ou 8, et leurs PS à 35. Lorsque vous modifiez les caractéristiques de combat, vous pouvez également améliorer les compétences et les équipements."
		},
		{
		  "Nom": "MAGES",
		  "Menace": "Moyen Simple",
		  "Récompense": "100 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Ville","Ruines"],
		  "Intelligence": "Humaine",
		  "Organisation": "Généralement solitaire",
		  "Note": "Les pouvoirs magiques présentés ci-dessus sont un exemple de ce que les mages peuvent utiliser pour s’en sortir face aux personnages joueurs. Vous pouvez personnaliser votre sorcier en le dotant de sorts, de rituels et d’envoûtements alternatifs décrits dans la section sur la magie, page 99."
		},
		{
		  "Nom": "BERSERKIR",
		  "Menace": "Moyen Fort",
		  "Récompense": "300 couronnes",
		  "Armure": "15",
		  "Taille": "Au moins 2 mètres de hauteur",
		  "Poids": "Au moins 200 Kg",
		  "Environnement": ["Skellige","Montagnes","Skellige"],
		  "Intelligence": "Fureur, combatif, animal",
		  "Organisation": "Solitaire ou en petite meute",
		  "Note": ""
		},
		{
		  "Nom": "SVINFYLKINGAR",
		  "Menace": "Moyen Fort",
		  "Récompense": "200 couronnes",
		  "Armure": "20",
		  "Taille": "Au moins 2 mètres de hauteur",
		  "Poids": "Au moins 200 Kg",
		  "Environnement": ["Skellige","Montagnes","Skellige"],
		  "Intelligence": "Fureur, combatif, animal",
		  "Organisation": "Solitaire ou en petite meute",
		  "Note": ""
		},
		{
		  "Nom": "ULFHEDNAR",
		  "Menace": "Moyen Fort",
		  "Récompense": "200 couronnes",
		  "Armure": "10",
		  "Taille": "Environ 1,5 mètres de hauteur",
		  "Poids": "Au moins 100 Kg",
		  "Environnement": ["Skellige","Montagnes","Skellige"],
		  "Intelligence": "Fureur, combatif, animal",
		  "Organisation": "Solitaire ou en petite meute",
		  "Note": ""
		},
		{
		  "Nom": "CHEF BANDIT",
		  "Menace": "Simple Complexe",
		  "Récompense": "40 couronnes",
		  "Armure": "Tête: 8<br>Torse: 12<br>Jambes: 12",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Ville","Route"],
		  "Intelligence": "Humaine",
		  "Organisation": "Bandes de 3 à 15 individus",
		  "Note": "Le niveau de compétences des bandits est extrêmement variable. Le profil présenté ici est celui d’un voyou de base, le genre de gros bras qui surveille l’entrepôt d’un criminel ou tend des embuscades aux voyageurs sur les routes. Vous pouvez tout à fait modifier les caractéristiques des bandits pour les rendre plus ou moins menaçants. Pour représenter un paysan ordinaire ou un scélérat de bas étage, diminuez ses RÉF et sa DEX à 3, et ses PS à 15. Sachez toutefois que ces brigands ne représenteront pas un défi pour les personnages combattants. Si vous voulez peupler les routes de voyous endurcis, augmentez leur RÉF et de DEX à 7 ou 8, et leurs PS à 35. Lorsque vous modifiez les caractéristiques de combat, vous pouvez également améliorer les compétences et les équipements."
		},
		{
		  "Nom": "SOUS-CHEF BANDIT",
		  "Menace": "Simple Moyen",
		  "Récompense": "15 couronnes",
		  "Armure": "Tête:0<br>Torse: 14<br>Jambes: 14",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Ville","Route"],
		  "Intelligence": "Humaine",
		  "Organisation": "Bandes de 3 à 15 individus",
		  "Note": "Le niveau de compétences des bandits est extrêmement variable. Le profil présenté ici est celui d’un voyou de base, le genre de gros bras qui surveille l’entrepôt d’un criminel ou tend des embuscades aux voyageurs sur les routes. Vous pouvez tout à fait modifier les caractéristiques des bandits pour les rendre plus ou moins menaçants. Pour représenter un paysan ordinaire ou un scélérat de bas étage, diminuez ses RÉF et sa DEX à 3, et ses PS à 15. Sachez toutefois que ces brigands ne représenteront pas un défi pour les personnages combattants. Si vous voulez peupler les routes de voyous endurcis, augmentez leur RÉF et de DEX à 7 ou 8, et leurs PS à 35. Lorsque vous modifiez les caractéristiques de combat, vous pouvez également améliorer les compétences et les équipements."
		},
		{
      "Nom": "RECRUES",
      "Menace": "Faible Complexe",
      "Récompense": "30 couronnes",
      "Armure": "Tête: 8, Torse: 14, Jambes: 12",
      "Taille": "Taille humaine",
      "Poids": "Poids humain",
      "Environnement": ["Partout"],
      "Intelligence": "Humaine",
      "Organisation": "En groupes",
      "Note": "Les recrues peuvent venir de n’importe quelle nation, l’entrée incluse ici est un exemple et les MJs devraient se sentir libres de redéfinir leurs équipements, leurs statistiques et même leurs capacités, pour mieux répondre à leurs préférences. Comme pour les bandits, les recrues peuvent être plus difficiles à combattre en améliorant leurs statistiques ou leurs PS. Le MJ peut aussi leur donner une meilleure armure ou de meilleures armes.<br>Les recrues seront parfois des unités criminelles. Sauf ordre direct, ils ne se battent généralement pas jusqu’à la mort. La plupart des déserteurs des différentes armées sont issus d’unités de recrues."
		},
		{
		  "Nom": "BANDITS DE GRAND CHEMIN",
		  "Menace": "Faible Complexe",
		  "Récompense": "40 couronnes",
		  "Armure": "Tête: 8,Torse: 12,Jambes: 12",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Ville","Route"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes",
		  "Note": "Les bandits de grand chemin ont souvent recours à des tactiques d’embuscade, soit en poursuivant ou en attirant des cibles vers des alliés, soit en posant des pièges le long de la route. (Pour connaître ces règles, reportez-vous au Livre de base, p. 55.) Les bandits de grand chemin peuvent également se déplacer à cheval. Si c’est le cas, ils ont des sacoches (+1 Contrôle), une selle de cavalerie et des bardes de cuir (10 PA). <br><b>Cheval:</b><br>Athlétisme +11 Mod. de contrôle +2 Vitesse 12 PS 40 Poids 100"
		},
		{
		  "Nom": "MERCENAIRES",
		  "Menace": "Faible Complexe",
		  "Récompense": "35 couronnes",
		  "Armure": "Tête: 5,Torse: 14,Jambes: 12",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes",
		  "Note": "<b>Cheval:</b> Athlétisme +11 Mod. de contrôle +2 Vitesse 12 PS 40 Poids 100 <br>Les mercenaires sont généralement soit engagés individuellement, soit organisés en groupes indépendants de taille importante, qui sont engagés par diverses nations sur tout le continent. L’argent est la principale motivation de toute unité de mercenaires, et la corruption, au lieu d’une confrontation directe, est parfois possible, même si elle est coûteuse. Les mercenaires peuvent être de n’importe quelle nation ou race, cette entrée ne doit être utilisée qu’à titre de référence, les MJs sont encouragés à la modifier s’ils en ont besoin. Certaines unités de mercenaires peuvent contenir ou être entièrement composées de biens de cavalerie."
		},
		{
		  "Nom": "PIRATES",
		  "Menace": "Faible Complexe",
		  "Récompense": "45 couronnes",
		  "Armure": "Tête: 3,Torse: 5,Jambes: 5",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Marin"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes",
		  "Note": "<b>Bateau:</b><br> Athlétisme - Mod. de contrôle 0 Vitesse 10 PS 60 Poids 610 <br>Les pirates se battent pour voler, rien de plus, rien de moins. Ils se battent rarement jusqu’à la mort, à moins d’être particulièrement désespérés ou d’avoir une motivation particulière. Un groupe de pirates n’engagera presque jamais le combat contre une cible à moins que les circonstances ne penchent fortement en leur faveur, et ils utiliseront tous les sales coups possibles pour s’en assurer. Vous trouverez ci-dessous les statistiques d’un petit bateau pirates typique, tel un cotre. Ces statistiques peuvent être modifiées pour représenter un navire plus grand, si besoin."
		},
		{
		  "Nom": "INFANTERIE NILFGAARDIENNE",
		  "Menace": "Faible Complexe",
		  "Récompense": "110 couronnes",
		  "Armure": "Tête: 16 Torse: 20 Jambes: 14",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes",
		  "Note": "Comme pour les bandits, l’infanterie peut être rendue plus difficile à combattre en améliorant ses statistiques ou ses PS. Le MJ peut aussi leur donner de meilleures armures ou de meilleures armes. <br> L’infanterie est l’épine dorsale des groupes d’armée des Noirs. Ce sont les soldats les plus communs, ceux que la plupart des gens rencontrent. Ils sont généralement loyaux, très disciplinés et bien entraînés. Comme dans toute armée, il y a des exceptions à cette règle, mais des punitions sévères et une supervision presque constante font que la plupart des soldats restent dans le rang."
		},
		{
		  "Nom": "AGENTS DES SERVICES SECRETS",
		  "Menace": "Faible Difficile",
		  "Récompense": "250 couronnes",
		  "Armure": "Tête: 8 Torse: 8 Jambes: 8",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "Généralement solitaire",
		  "Note": "Les agents se procurent souvent des armures et des armes différentes pour mieux s’infiltrer dans les lieux ou se créer de fausses identités. Bien que cette entrée soit conçue comme un espion de Nilfgaard, elle peut facilement être modifiée pour devenir un espion de n’importe quel pays."
		},
		{
		  "Nom": "PACIFICATEUR DE GEMMERA",
		  "Menace": "Fort Simple",
		  "Récompense": "500 couronnes",
		  "Armure": "Tête: 14 Torse: 16 Jambes: 16",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes, petites unités",
		  "Note": "Les pacificateurs existent pour répandre la terreur. Cela signifie qu’ils se livrent régulièrement à des actions vraiment terribles, comme le meurtre et le viol, afin de rendre passifs les civils nouvellement conquis. Ces actions sont évidemment délicates, et peuvent facilement être soit ignorées entièrement, soit dissimulées en coulisses si le MJ le souhaite."
		},
		{
		  "Nom": "CHEVALIERS NILFGAARDIENS",
		  "Menace": "Fort Complexe",
		  "Récompense": "650 couronnes",
		  "Armure": "Tête : 30 Torse: 30 Jambes: 30",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes, petites unités",
		  "Note": "<b>Cheval de guerre</b><br>Athlétisme +12 Mod. de contrôle -1 Vitesse 11 PS 50 Poids 270 <br>Les chevaliers peuvent être rendus moins difficiles à combattre en diminuant leurs statistiques ou leurs PS. Le MJ peut également leur donner une armure et un équipement plus légers.<br>Les chevaliers se battent presque toujours à cheval. Ils disposent de sacoches, d’une selle de cavalerie (+1 aux jets de Contrôle), d’oeillères (+1 pour calmer la monture) et de barde de mailles (15 PA)."
		},
		{
		  "Nom": "SOLDATS DES ROYAUMES DU NORD",
		  "Menace": "Faible Complexe",
		  "Récompense": "100 couronnes",
		  "Armure": "Tête: 14 Torse: 14 Jambes: 14",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes",
		  "Note": "Comme pour les bandits, l’infanterie peut être rendue plus difficile à combattre en améliorant ses statistiques ou ses PS. Le MJ peut aussi leur donner une meilleure armure ou de meilleures armes.<br>Les soldats du Nord peuvent provenir de n’importe quel pays, rassemblés sous la bannière des Royaumes du Nord. Dans cette optique, les armes ou armures dont ils sont équipés peuvent facilement être modifiées pour s’adapter à une nation ou une unité particulière."
		},
		{
		  "Nom": "CAVALERIE DE KAEDWEN",
		  "Menace": "Moyen Complexe",
		  "Récompense": "450 couronnes",
		  "Armure": "Tête: 16 Torse: 16 Jambes: 16",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes, petites unités",
		  "Note": "<b>Cheval</b><br>Athlétisme +11 Mod. de contrôle +2 Vitesse 12 PS 40 Poids 100<br>Le terrain de Kaedwen ne convient pas aux chevaux de guerre, leur cavalerie est donc généralement déployée sur des montures agiles. Les cavaliers Kaedweniens se battent presque toujours à cheval. Ils disposent de sacoches, d’une selle de cavalerie (+1 aux jets de Contrôle), d’oeillères (+1 pour calmer la monture) et de barde de cuir (10 PA)."
		},
		{
		  "Nom": "STRIES BLEUES",
		  "Menace": "Moyen Difficile",
		  "Récompense": "300 couronnes",
		  "Armure": "Tête: 14 Torse: 16 Jambes: 12",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes",
		  "Note": "Les Stries Bleues utilisent presque toujours des tactiques d’embuscade et de fuite, soit en poursuivant ou en attirant des cibles dans les rangs des alliés, soit en posant des pièges le long de la route. (Voir le Livre de base, p. 55)"
		},
		{
		  "Nom": "HALLEBARDIERS REDANIENS",
		  "Menace": "Moyen Simple",
		  "Récompense": "400 couronnes",
		  "Armure": "Tête: 12 Torse: 14 Jambes: 14",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes, petites unités",
		  "Note": ""
		},
		{
		  "Nom": "MARAUDEURS SCOIA’TAEL",
		  "Menace": "Moyen Complexe",
		  "Récompense": "500 couronnes",
		  "Armure": "Tête: 10 Torse: 10 Jambes: 10",
		  "Taille": "Taille naine",
		  "Poids": "Poids naine",
				"Environnement": ["Ville","Route","Forêts"],
		  "Intelligence": "Humaine",
		  "Organisation": "Petits groupes",
		  "Note": "Bien qu’ils soient conçus avec des équipements des Races Anciennes, les maraudeurs peuvent être ré-équipés pour utiliser des équipements banals si le MJ le souhaite. Le MJ peut aussi augmenter la difficulté en leur donnant de meilleures armures ou armes de la section « Armures des Races Anciennes ». Des bombes peuvent également être données aux maraudeurs, mais ces armes sont extrêmement mortelles et peuvent rapidement tuer un groupe de joueurs.<br>Bien que les elfes soient le plus courant, les Scoia’tael font aussi appel à d’autres membres des Races Anciennes comme les halfelins, les gnomes et les nains."
		},
		{
		  "Nom": "VETERANS SCOIA’TAEL",
		  "Menace": "Moyen Complexe",
		  "Récompense": "500 couronnes",
		  "Armure": "Tête: 20 Torse: 20 Jambes: 20",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
				"Environnement": ["Ville","Route","Forêts"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes, petites unités",
		  "Note": "<b>Cheval:</b><br>Athlétisme +11 Mod. de contrôle +3 Vitesse 12 PS 40 Poids 100<br>Bien qu’ils soient conçus avec des équipements des Races Anciennes, les vétérans peuvent être ré-équipés pour utiliser des équipements banals si le MJ le souhaite. Le MJ peut aussi augmenter la difficulté en leur donnant de meilleures armures ou armes de la section « Armures des Races Anciennes ». Des bombes peuvent également être données aux maraudeurs, mais ces armes sont extrêmement mortelles et peuvent rapidement tuer un groupe de joueurs.<br>Les vétérans se battent parfois à cheval. Ils disposent de sacoches, d’une selle de course (+2 aux jets de Contrôle), d’oeillères (+1 pour calmer la monture) et de bardes de cuir (10 PA)."
		},
		{
		  "Nom": "DEFENSEURS DE MAHAKAM",
		  "Menace": "Moyen Complexe",
		  "Récompense": "600 couronnes",
		  "Armure": "Tête : 8",
		  "Torse : 20": "Jambes : 20",
		  "Taille": "Taille naine",
		  "Poids": "Poids nain",
		  "Environnement": ["Mahakam"],
		  "Intelligence": "Humaine",
		  "Organisation": "En groupes",
		  "Note": "Bien qu’ils soient conçus avec des équipements des Races Anciennes, les Défenseurs peuvent être ré-équipés pour utiliser des équipements banals si le MJ le souhaite. Le MJ peut aussi augmenter la difficulté en leur donnant de meilleures armures ou armes de la section « Armures des Races Anciennes »."
		}
	],
	"Monstre": [
		{
		  "Nom": "GOULE",
		  "Type": "NÉCROPHAGE",
		  "Menace": "Faible Difficile",
		  "Récompense": "30 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,25 m au garrot",
		  "Poids": "Environ 86 kg",
		  "Environnement": ["Champs de bataille","Cimetière"],
		  "Intelligence": "Aussi intelligente qu’un chien",
		  "Organisation": "Groupes de 3 à 6 individus",
		  "Note": ""
		},
		{
		  "Nom": "GUENAUDE SÉPULCRALE",
		  "Type": "NÉCROPHAGE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "500 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,75 m",
		  "Poids": "Environ 80 kg",
		  "Environnement": ["Cimetière","Grotte"],
		  "Intelligence": "Aussi intelligente qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "Même les mages les plus érudits butent sur l’origine de la magie qui émane des cercles de crânes des guenaudes sépulcrales. Dans l’ensemble, on considère qu’ils tirent leurs pouvoirs des démons peuplant le vide qui sépare les différents plans de l’univers."
		},
		{
		  "Nom": "NOYEURS",
		  "Type": "NÉCROPHAGE",
		  "Menace": "Faible Simple",
		  "Récompense": "10 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
		  "Environnement": ["Marin","Egouts"],
		  "Intelligence": "Aussi intelligent qu’un poisson",
		  "Organisation": "Groupes de 3 à 6 individus",
		  "Note": "Ils ont beau croire que les noyeurs sont des criminels revenus à la vie, beaucoup de citadins de la région du Pontar sont prêts à payer un bon prix pour obtenir des cerveaux de ces monstres. Ils les font bouillir dans un ragoût pour obtenir, paraît-il, un aphrodisiaque extrêmement puissant."
		},
		{
		  "Nom": "FANTÔMES",
		  "Type": "SPECTRE",
		  "Menace": "Faible Difficile",
		  "Récompense": "30 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Intangible",
		  "Environnement": ["Champs de bataille","Cimetière"],
		  "Intelligence": "Guidé par ses émotions",
		  "Organisation": "Groupes de 3 à 21 individus",
		  "Note": "Les armes d’un fantôme sont la manifestation du pouvoir qu’il acquiert au moment de sa création. Lorsqu’il meurt, on ne peut pas ramasser sa lanterne et son épée qui s’évaporent avec le reste de son corps."
		},
		{
		  "Nom": "SPECTRE DE MIDI",
		  "Type": "SPECTRE",
		  "Menace": "Moyen Difficile",
		  "Récompense": "800 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Intangible",
		  "Environnement": ["Ville"],
		  "Intelligence": "Consumé par la haine",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "LOUPS",
		  "Type": "BÊTE",
		  "Menace": "Facile Simple",
		  "Récompense": "10 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 0,8 m",
		  "Poids": "Environ 68 kg",
		  "Environnement": ["Forêts","Plaines"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Meutes de 3 à 6 individus",
		  "Note": ""
		},
		{
		  "Nom": "WARGS",
		  "Type": "BÊTE",
		  "Menace": "Facile Simple",
		  "Récompense": "10 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 0,8 m",
		  "Poids": "Environ 68 kg",
		  "Environnement": ["Forêts","Plaines"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Meutes de 3 à 6 individus",
		  "Note": "Les wargs sont plus grands que les loups, arborent une fourrure brun-roux et possèdent des yeux rouges et brillants. Au vu de leur comportement, ils paraissent plus intelligents que les loups."
		},
		{
		  "Nom": "LOUPS-GAROUS",
		  "Type": "CRÉATURE MAUDITE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "500 couronnes",
		  "Armure": "8",
		  "Taille": "Environ 2,5 m",
		  "Poids": "Environ 140 kg",
		  "Environnement": ["Forêts","Ville"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "Un personnage affligé de lycanthropie a 30 % de chance de se transformer en loup-garou chaque nuit au moment où la lune se lève. Quand il est sous sa forme bestiale, il devient un prédateur sanguinaire doté d’une intelligence humaine qui a soif de meurtre. Si c’est un personnage joueur, le MJ en prend le contrôle jusqu’au lever du jour. Lorsqu’il est transformé en monstre, le lycanthrope acquiert les armes, l’armure et les capacités d’un loup-garou. Le personnage ajoute également les bonus suivants à ses caractéristiques : Réflexes +2,  Corps +3,  Vitesse +4,  Empathie –5"
		},
		{
		  "Nom": "GRIFFONS",
		  "Type": "HYBRIDE",
		  "Menace": "Difficile Complexe",
		  "Récompense": "1200 couronnes",
		  "Armure": "8",
		  "Taille": "Environ 2 m au garrot",
		  "Poids": "Environ 900 kg",
		  "Environnement": ["Montagnes"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Seul ou en couple",
		  "Note": ""
		},
		{
		  "Nom": "SIRÈNES",
		  "Type": "HYBRIDE",
		  "Menace": "Facile Complexe",
		  "Récompense": "20 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 3 m de long",
		  "Poids": "Environ 120 kg",
		  "Environnement": ["Marin"],
		  "Intelligence": "Aussi intelligente qu’un humain",
		  "Organisation": "Groupes de 3 à 6 individus",
		  "Note": ""
		},
		{
		  "Nom": "ARACHAS",
		  "Type": "INSECTOÏDE",
		  "Menace": "Fort Complexe",
		  "Récompense": "1000 couronnes",
		  "Armure": "20",
		  "Taille": "Environ 3 m",
		  "Poids": "Environ 800 kg",
		  "Environnement": ["Marécages"],
		  "Intelligence": "Aussi intelligente qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "ENDRIAGUES",
		  "Type": "INSECTOÏDE",
		  "Menace": "Facile Difficile",
		  "Récompense": "30 couronnes",
		  "Armure": "8",
		  "Taille": "Environ 2,5 m",
		  "Poids": "Environ 200 kg",
		  "Environnement": ["Marécages"],
		  "Intelligence": "Aussi intelligente qu’un chien",
		  "Organisation": "Groupes de 3 à 9 individus",
		  "Note": "Les reines endriagues ressemblent tant aux arachas qu’on peut facilement les confondre. Lorsque les personnages s’aventurent dans un nid d’endriague, le MJ peut utiliser les caractéristiques des arachas pour représenter la reine.\nÉpines de bourdon Un bourdon endriague projette ses épines sur un rayon de 5 m autour de lui. On peut esquiver ou bloquer les épines (SD 15). La cible subit 1d6 points de dégâts empoisonnés pour chaque point de marge d’échec.\nQueue de guerrière Une guerrière endriague possède une grande queue qui inflige 4d6+2 points de dégâts ayant 50 % de chance d’être empoisonnés.\nPinces d’ouvrière Les pinces de l’ouvrière endriague ont 25 % de chance d’infliger des dégâts empoisonnés."
		},
		{
		  "Nom": "GOLEMS",
		  "Type": "ÉLÉMENTAIRE",
		  "Menace": "Fort Simple",
		  "Récompense": "1200 couronnes",
		  "Armure": "20",
		  "Taille": "Environ 2,5 m",
		  "Poids": "Environ 900 kg",
		  "Environnement": ["Ruines"],
		  "et": "des tours de sorciers",
		  "Intelligence": "Incapable de réfléchir",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "FIELLONS",
		  "Type": "VESTIGE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1500 couronnes",
		  "Armure": "10",
		  "Taille": "Environ 4 m au garrot",
		  "Poids": "Environ 1500 kg",
		  "Environnement": ["Forêts"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "NEKKERS",
		  "Type": "OGROÏDE",
		  "Menace": "Facile Complexe",
		  "Récompense": "10 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1 m",
		  "Poids": "Environ 13 kg",
		  "Environnement": ["Forêts","Plaines"],
		  "Intelligence": "Aussi intelligent qu’un",
		  "humain": "simplet",
		  "Organisation": "Bandes de 3 à 12 individus",
		  "Note": ""
		},
		{
		  "Nom": "CHEF NEKKER",
		  "Type": "OGROÏDE",
		  "Menace": "Facile Complexe",
		  "Récompense": "10 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1 m",
		  "Poids": "Environ 13 kg",
		  "Environnement": ["Forêts","Plaines"],
		  "Intelligence": "Aussi intelligent qu’un",
		  "humain": "simplet",
		  "Organisation": "Bandes de 3 à 12 individus",
		  "Note": "Les chefs nekkers sont en général plus grands que les autres membres de leur espèce. Certains savants pensent qu’il s’agit d’une autre race de nekker, mais il est plus probable que, comme chez les humains, les monstres élisent les plus forts comme chef. On pense qu’ils arborent des peintures de guerre, ce qui expliquerait la teinte rouge de leur peau."
		},
		{
		  "Nom": "TROLLS DE PIERRE",
		  "Type": "OGROÏDE",
		  "Menace": "Moyen Difficile",
		  "Récompense": "800 couronnes",
		  "Armure": "20",
		  "Taille": "Environ 2 m",
		  "Poids": "Environ 150 kg",
		  "Environnement": ["Montagnes","Vallées"],
		  "Intelligence": "Aussi intelligent qu’un",
		  "humain": "simplet",
		  "Organisation": "Solitaire ou groupes de 2 à 3",
		  "individus": "undefined",
		  "Note": "Il n’est pas rare de trouver des trolls des cavernes vivant sous des ponts ou à proximité, et parfois des trolls de pierre. Les villes profitent souvent de leur force et de leurs talents de bâtisseurs pour les assigner à la maintenance des ponts et, parfois, pour qu’ils s’occupent de percevoir les droits de passage. Les autorités s’accommodent très bien de ces employés qui ne se plaignent presque jamais et qu’elles peuvent payer avec de la vodka."
		},
		{
		  "Nom": "WYVERNS",
		  "Type": "DRACONIDE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1000 couronnes",
		  "Armure": "10",
		  "Taille": "Environ 2 m",
		  "Poids": "Environ 900 kg",
		  "Environnement": ["Montagnes","Vallées"],
		  "Intelligence": "Aussi intelligente qu’un chien",
		  "Organisation": "Solitaire ou par couple",
		  "Note": "Depuis des années, les armures que revêtent la noblesse et les chevaliers ainsi que les tenues des mages tenant à impressionner leurs pairs comportent des écailles de draconides. Les écailles tannées pour obtenir du cuir de draconide offrent une protection efficace et sont tellement solides que les ensembles d’armure fabriqués dans cette matière font partie des héritages familiaux qui se transmettent de génération en génération."
		},
		{
		  "Nom": "KATAKANS",
		  "Type": "VAMPIRE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1500 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 2 m",
		  "Poids": "Environ 115 kg",
		  "Environnement": ["Ruines","Grottes","Ville"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "AGUARA",
		  "Type": "VESTIGE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "800 couronnes",
		  "Armure": "8",
		  "Taille": "Humaine",
		  "Poids": "Humain",
		  "Environnement": ["Fôrets"],
		  "Intelligence": "Aussi intelligente qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "ALGOULES",
			  "Type": "NÉCROPHAGE",
		  "Menace": "Moyen Simple",
		  "Récompense": "50 couronnes",
		  "Armure": "5",
		  "Taille": "Environ 1,30 mètre au garrot",
		  "Poids": "Environ 90kg",
			  "Environnement": ["Champs de bataille","Cimetière"],
		  "Intelligence": "À peu près aussi intelligent qu'un chien",
		  "Organisation": "Bandes de 3 à 15 goules",
		  "Note": ""
		},
		{
		  "Nom": "ARACHNOMORPHE",
			  "Type": "INSECTOÏDE",
		  "Menace": "Faible Difficile",
		  "Récompense": "25 couronnes",
		  "Armure": "5",
		  "Taille": "Entre 1.50 et 2 mètres",
		  "Poids": "Environ 50kg",
			  "Environnement": ["Forêts","Marécages","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Bandes de 5 à 15 individus",
		  "Note": ""
		},
		{
		  "Nom": "BANSHEE",
			  "Type": "SPECTRE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "250 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Intangible",
			  "Environnement": ["Déserts","Ville"],
		  "Intelligence": "Guidé par ses émotions",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "DJINN",
			  "Type": "VESTIGE",
		  "Menace": "Fort Difficile",
		  "Récompense": "2 000 couronnes",
		  "Armure": "0",
		  "Taille": "Variable",
		  "Poids": "Intangible",
			  "Environnement": ["Invocation"],
		  "Intelligence": "Assez intelligent pour négocier",
		  "Organisation": "Solitaire",
		   "Note": "DERNIER RECOURS<br> Lorsqu'un djinn tombe en dessous de 10 PS, il lui faudra un tour pour préparer une énorme téléportation tout en maintenant les tempêtes ou autres attaques actives. Au début de son prochain tour, le djinn disparaîtra et ne laissera aucune trace de sa nouvelle localisation. Si le djinn tombe à 0 PS, il est incapable d'exécuter ce sort en un instant. Mais après 30 minutes de repos, le djinn se téléportera instantanément, à condition qu'il n'ait pas été piégé dans un récipient."
		},
		{
		  "Nom": "ÉCHIDNA",
			  "Type": "HYBRIDE",
		  "Menace": "Moyen Simple",
		  "Récompense": "50 couronnes",
		  "Armure": "5",
		  "Taille": "Environ 3 mètres de long",
		  "Poids": "Environ 150kg",
			  "Environnement": ["Marin"],
		  "Intelligence": "Humaine",
		  "Organisation": "Bandes de 3 à 6 individus souvent mélangé avec des sirènes",
		  "Note": ""
		},
		{
		  "Nom": "EKIMME",
			  "Type": "VAMPIRE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "500 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 2 mètres",
		  "Poids": "Environ 100kg",
			  "Environnement": ["Grotte","Ruines","Ville"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "FOËNARD",
			  "Type": "DRACONIDE",
		  "Menace": "Fort Simple",
		  "Récompense": "950 couronnes",
		  "Armure": "8",
		  "Taille": "Environ 2 mètres",
		  "Poids": "Environ 800kg",
			  "Environnement": ["Montagnes","Plaines"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire ou en couple",
		  "Note": ""
		},
		{
		  "Nom": "GLOUTON DES VASIERES",
			  "Type": "INSECTOÏDE",
		  "Menace": "Moyen Difficile",
		  "Récompense": "600 couronnes",
		  "Armure": "5",
		  "Taille": "Jusqu'à 4 mètres",
		  "Poids": "Jusqu'à 1 000kg",
			  "Environnement": ["Marécages","Marin"],
		  "Intelligence": "Aussi intelligent qu’un poisson",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "OUVRIÈRE KIKIMORRHE",
			  "Type": "INSECTOÏDE",
		 "Menace": "Moyen Complexe",
		  "Récompense": "50 couronnes",
		  "Armure": "10",
		  "Taille": "Entre 1 et 3 mètres",
		  "Poids": "Entre 180kg et 300kg",
			  "Environnement": ["Marécages","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Colonies de 3 à 20",
		  "Note": "Les ouvriers sont plus petites et plus rapides que les autres kikimorrhes. Elles ont une VIT de 10 et un +2 pour l'athlétisme et l'esquive/évasion."
		},
		{
		  "Nom": "GUERRIÈRE KIKIMORRHE",
		  "Menace": "Moyen Complexe",
			  "Type": "INSECTOÏDE",
		  "Récompense": "50 couronnes",
		  "Armure": "20",
		  "Taille": "Entre 1 et 3 mètres",
		  "Poids": "Entre 180kg et 300kg",
			  "Environnement": ["Marécages","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Colonies de 3 à 20",
		  "Note": "Les guerrières sont plus grosses et plus fortes que les ouvrières. Elles ont 20 d’armures et sont capables de commander les ouvrières autour d'eux. Ces commandes ne peuvent jamais être plus complexes que  \"Apportez ça\". \"Attaquez ceci\" ou \"Creusez un tunnel là-bas\"."
		},
		{
		  "Nom": "REINE KIKIMORRHE",
			  "Type": "INSECTOÏDE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "50 couronnes",
		  "Armure": "20",
		  "Taille": "Entre 1 et 3 mètres",
		  "Poids": "Entre 180kg et 300kg",
			  "Environnement": ["Marécages","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Colonies de 3 à 20",
		  "Note": "Les reines sont un spectacle rare. Elles sont le type de kikimorrhe le plus gros et le plus dangereux. Elles sont immunisés contre tous les effets, même le feu, ont une résistance aux attaques tranchantes, perforantes et contondantes, 20 d’armures et leurs attaques mettent la cible au sol. Elles sont également très lentes, n'ayant donc qu'une VIT de 3."
		},
		{
		  "Nom": "KOCHTCHEÏ",
			  "Type": "BÊTE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "250 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
			  "Environnement": ["Invocation"],
		  "Intelligence": "Humaine",
		  "Organisation": "Bandes de 3 à 15 individus",
		  "Note": ""
		},
		{
		  "Nom": "MULA",
			  "Type": "VAMPIRE",
		 "Menace": "Dur Difficile",
		  "Récompense": "1 500 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 2 mètres",
		  "Poids": "Environ 120kg",
			  "Environnement": ["Ruines","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "RAGE SANGUINE<br> Dans cet état, ses yeux commencent à briller et il ne se transforme pas en brouillard. Ses attaques gagnent +2 Fia et ses griffes attaquent 2 fois par tour. Rage sanguine se termine après 5 tours ou si le mula subit une blessure critique."
		},
		{
		  "Nom": "NECROPHAGE",
			  "Type": "NÉCROPHAGE",
		"Menace": "Moyen Simple",
		  "Récompense": "100 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1.60 mètres",
		  "Poids": "Environ 60kg",
			  "Environnement": ["Déserts","Cimetière"],
		  "Intelligence": "Peut-être au niveau humain",
		  "Organisation": "Solitaire",
		  "Note": "COMPAGNONS FANTOMATIQUES<br> Les barghests invoqués de cette manière tiendront compte de tous les ordres du nécrophage et ne disparaîtront pas à moins qu'ils ne soient tués ou que le nécrophage ne meure. Pour cette raison, le territoire d'un nécrophage est parfois gardé par de petits groupes de barghests."
		},
		{
		  "Nom": "NEKURAT",
			  "Type": "VAMPIRE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1 750 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 2 mètres",
		  "Poids": "Environ 100kg",
			  "Environnement": ["Grotte","Ruines","Ville"],
		  "Intelligence": "Au-dessus du niveau humain",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "PENITENT",
			  "Type": "SPECTRE",
		 "Menace": "Fort Simple",
		  "Récompense": "1 000 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Intangible",
			  "Environnement": ["Ville"],
		  "Intelligence": "Consumé par la colère",
		  "Organisation": "Solitaire, mais souvent entouré de spectres",
		  "Note": "COMMANDEMENT DES SPECTRES<br> Les ordres ne sont que des tactiques humaines de base et donc jamais plus complexes que \"Tuez-les d'abord\", \"Gardez celui-ci pour la fin\" ou \"Retraite\"."
		},
		{
		  "Nom": "PIQUETEUR",
			  "Type": "NÉCROPHAGE",
		"Menace": "Faible Difficile",
		  "Récompense": "50 couronnes",
		  "Armure": "5",
		  "Taille": "Taille humaine",
		  "Poids": "Environ 90kg",
			  "Environnement": ["Champs de bataille","Cimetière"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Bandes de 3 à 6 individus, souvent avec des putréfacteurs",
		  "Note": ""
		},
		{
		  "Nom": "SPECTRE DE MINUIT",
			  "Type": "SPECTRE",
		 "Menace": "Moyen Difficile",
		  "Récompense": "750 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Intangible",
			  "Environnement": ["Ville","Plaines"],
		  "Intelligence": "Consumé par le chagrin",
		  "Organisation": "Solitaire",
		  "Note": "VEILLEUSE<br> Tant que ces copies existent, tous les êtres vivants dans un rayon de 30 m subissent 3 dégâts par tour. Une fois que toutes les copies sont vaincues, le spectre de minuit réapparaît. Les copies elles-mêmes n'attaqueront pas mais défendront et partageront les mêmes traits qu'un spectre de minuit normal. Frapper une copie la tuera."
		},
		{
		  "Nom": "TROLL DE GLACE",
			  "Type": "OGROÏDE",
		"Menace": "Moyen Difficile",
		  "Récompense": "850 couronnes",
		  "Armure": "20",
		  "Taille": "Environ 4 mètres",
		  "Poids": "Environ 150kg",
			  "Environnement": ["Montagnes"],
		  "Intelligence": "Aussi intelligent qu’un humain simplet",
		  "Organisation": "Solitaire ou groupes de 2 à 3 individus",
		  "Note": ""
		},
		{
		  "Nom": "GUERRIER DE LA CHASSE SAUVAGE",
			  "Type": "HUMANOÏDE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "100 couronnes",
		  "Armure": "Tète : 30, Torse : 30, Jambes : 30",
		  "Taille": "Taille Aen Elle",
		  "Poids": "Poids Aen Elle",
			  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "Bandes de 3+ individus, souvent accompagné de molosses",
		  "Note": "<b>Bouclier<b><br> Certains guerriers portent des boucliers. Bien que les porteurs de boucliers soient rares, les guerriers feront bon usage des boucliers en essayant de bloquer les attaques et en particulier les projectiles visant leurs camarades. <br><b>Cavalier</b><br> Certains guerriers possèdent un cheval de guerre fidèle. Ces soi-disant cavaliers ont un bonus +5 supplémentaire pour les jets de contrôle avec leurs montures."
		},
		{
		  "Nom": "MOLOSSE DE LA CHASSE SAUVAGE",
			  "Type": "ÉLÉMENTAIRE",
		  "Menace": "Moyen Simple",
		  "Récompense": "50 couronnes",
		  "Armure": "10",
		  "Taille": "Environ 80 centimètres",
		  "Poids": "Environ 80kg",
			  "Environnement": ["Partout"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Bandes de 3+ individus",
		  "Note": ""
		},
		{
		  "Nom": "NAVIGATRICE DE LA CHASSE SAUVAGE",
		  "Menace": "Moyen Difficile",
			  "Type": "HUMANOÏDE",
		 "Récompense": "150 couronnes",
		  "Armure": "Tête : 18, Torse : 18, Jambes : 18",
		  "Taille": "Taille Aen Elle",
		  "Poids": "Poids Aen Elle",
			  "Environnement": ["Partout"],
		  "Intelligence": "Humaine",
		  "Organisation": "Solitaire, accompagné par des guerriers et molosses",
		  "Note": "Un navigateur est capable d'utiliser les sorts: Dissipation Invocation de bâton Aire de glace Grêle de Cary Vague du Naglfar Tryferi Gaeaf"
		},
		{
		  "Nom": "ABAYA",
			  "Type": "NÉCROPHAGE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "450 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,75m",
		  "Poids": "Jusqu’à 80kg",
			  "Environnement": ["Marin","Marécages"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "ALPYRE",
			  "Type": "VAMPIRE",
		  "Menace": "Difficile Complexe",
		  "Récompense": "1000 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,5 m",
		  "Poids": "Environ 75 kg",
			  "Environnement": ["Ville","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "AMAROK",
			  "Type": "CRÉATURE MAUDITE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "650 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1 m",
		  "Poids": "Environ 70 kg",
			  "Environnement": ["Forêts","Plaines"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "BARGHEST (fan)",
			  "Type": "SPECTRE",
		  "Menace": "Facile Complexe",
		  "Récompense": "50 couronnes",
		  "Armure": "8",
		  "Taille": "Taille",
		  "Poids": "Poids",
			  "Environnement": ["Invocation"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Meutes de 3 à 6",
		  "Note": ""
		},
		{
		  "Nom": "BASILIC",
		  "Menace": "Difficile Complexe",
			  "Type": "DRACONIDE",
		  "Récompense": "800 couronnes",
		  "Armure": "8",
		  "Taille": "1,5 m au garrot",
		  "Poids": "Environ 70 kg",
			  "Environnement": ["Egouts","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire ou en couple",
		  "Note": ""
		},
		{
		  "Nom": "BRUMELIN (fan)",
			  "Type": "NÉCROPHAGE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "450 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,5 m",
		  "Poids": "Environ 65 kg",
			  "Environnement": ["Marécages"],
		  "Intelligence": "Aussi intelligent qu’un humain stupide",
		  "Organisation": "Solitaire, rarement en petits groupes",
		  "Note": ""
		},
		{
		  "Nom": "COCATRIX (fan)",
		  "Menace": "Moyen Complexe",
			  "Type": "DRACONIDE",
		  "Récompense": "600 couronnes",
		  "Armure": "5",
		  "Taille": "1,2 m au garrot",
		  "Poids": "Environ 500 kg",
			  "Environnement": ["Ruines","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "COUVIN (fan)",
			  "Type": "CRÉATURE MAUDITE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "500 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 0,5 m",
		  "Poids": "Environ 40 kg",
		  "Environnement": ["Partout"],
		  "Intelligence": "Aussi intelligent qu’un humain stupide",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "COUVIN TRANSFORMÉ (fan)",
			  "Type": "CRÉATURE MAUDITE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "500 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 0,5 m",
		  "Poids": "Environ 40 kg",
		  "Environnement": ["Partout"],
		  "Intelligence": "Aussi intelligent qu’un humain stupide",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "CYCLOPE (fan)",
			  "Type": "OGROÏDE",
		  "Menace": "Difficile Complexe",
		  "Récompense": "1750 couronnes",
		  "Armure": "10",
		  "Taille": "Jusqu’à 5 m",
		  "Poids": "Environ 1600 kg",
		  "Environnement": ["Montagnes","Grotte","Plaines"],
		  "Intelligence": "Aussi intelligent qu’un humain stupide",
		  "Organisation": "Solitaire",
		  "Note": "Bien que particulièrement stupides, les cyclopes sont néanmoins capables de fabriquer des pièges étonnamment sophistiqués. Ils utilisent souvent ces compétences pour protéger leurs repaires."
		},
		{
		  "Nom": "DEVOREUR",
			  "Type": "NÉCROPHAGE",
		  "Menace": "Facile Complexe",
		  "Récompense": "50 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 2 m",
		  "Poids": "Environ 150 kg",
		  "Environnement": ["Champs de bataille","Cimetière","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un humain stupide",
		  "Organisation": "Solitaire, parfois avec des goules",
		  "Note": ""
		},
		{
		  "Nom": "DOPPLER",
			  "Type": "VESTIGE",
		  "Menace": "Moyen Difficile",
		  "Récompense": "1000 couronnes",
		  "Taille": "Environ 1,5 m",
		  "Poids": "Environ 100 kg",
		  "Environnement": ["Partout"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "DRAGON NOIR (fan)",
			  "Type": "DRACONIDE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1500+ couronnes",
		  "Armure": "20",
		  "Taille": "Variable, jusqu’à 6m au garrot",
		  "Poids": "Variable, jusqu’à 1500 kg",
			"Environnement": ["Forêts","Grotte","Montagnes"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "Les dragons se présentent sous différentes espèces, représentées par des couleurs. Les plus connues sont : le noir, le rouge, le blanc et le vert. Les dragons dorés n’existent presque exclusivement que dans les légendes, et les dragons de roche sont considérés comme éteints. Les statistiques et les compétences indiquées représentent les plus petites couleurs de dragons telles que le vert, le noir et le blanc ; le MJ devrait se sentir libre d’en ajouter pour représenter les plus grandes variétés. \nLes dragons noirs soufflent un gaz nocif, infligeant 5d6 dégâts et 2d6 d’ablation. Ils ont également une armure deux fois plus importante que celle indiquée."
		},
		{
		  "Nom": "DRAGON VERT (fan)",
			  "Type": "DRACONIDE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1500+ couronnes",
		  "Armure": "10",
		  "Taille": "Variable, jusqu’à 6m au garrot",
		  "Poids": "Variable, jusqu’à 1500 kg",
			"Environnement": ["Forêts","Grotte","Montagnes"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "Les dragons se présentent sous différentes espèces, représentées par des couleurs. Les plus connues sont : le noir, le rouge, le blanc et le vert. Les dragons dorés n’existent presque exclusivement que dans les légendes, et les dragons de roche sont considérés comme éteints. Les statistiques et les compétences indiquées représentent les plus petites couleurs de dragons telles que le vert, le noir et le blanc ; le MJ devrait se sentir libre d’en ajouter pour représenter les plus grandes variétés.\nLes dragons verts soufflent de la vapeur, infligeant 6d6 dégâts qui sont également stupéfiants. Ils sont amphibies."
		},
		{
		  "Nom": "DRAGON BLANC (fan)",
			  "Type": "DRACONIDE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1500+ couronnes",
		  "Armure": "10",
		  "Taille": "Variable, jusqu’à 6m au garrot",
		  "Poids": "Variable, jusqu’à 1500 kg",
			"Environnement": ["Forêts","Grotte","Montagnes"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "Les dragons se présentent sous différentes espèces, représentées par des couleurs. Les plus connues sont : le noir, le rouge, le blanc et le vert. Les dragons dorés n’existent presque exclusivement que dans les légendes, et les dragons de roche sont considérés comme éteints. Les statistiques et les compétences indiquées représentent les plus petites couleurs de dragons telles que le vert, le noir et le blanc ; le MJ devrait se sentir libre d’en ajouter pour représenter les plus grandes variétés. \nLes dragons blancs soufflent un brouillard glacial, infligeant 6d6 dégâts et provoquant l’effet Gel."
		},
		{
		  "Nom": "DRAGON ROUGE (fan)",
			  "Type": "DRACONIDE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1500+ couronnes",
		  "Armure": "10",
		  "Taille": "Variable, jusqu’à 6m au garrot",
		  "Poids": "Variable, jusqu’à 1500 kg",
			"Environnement": ["Forêts","Grotte","Montagnes"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "Les dragons se présentent sous différentes espèces, représentées par des couleurs. Les plus connues sont : le noir, le rouge, le blanc et le vert. Les dragons dorés n’existent presque exclusivement que dans les légendes, et les dragons de roche sont considérés comme éteints. Les statistiques et les compétences indiquées représentent les plus petites couleurs de dragons telles que le vert, le noir et le blanc ; le MJ devrait se sentir libre d’en ajouter pour représenter les plus grandes variétés. \nLes dragons rouges et les dorés crachent du feu, infligeant 6d6 dégâts et l’effet Incinération."
		},
		{
		  "Nom": "DRAGON DORÉ (fan)",
			  "Type": "DRACONIDE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1500+ couronnes",
		  "Armure": "10",
		  "Taille": "Variable, jusqu’à 6m au garrot",
		  "Poids": "Variable, jusqu’à 1500 kg",
			"Environnement": ["Forêts","Grotte","Montagnes"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "Les dragons se présentent sous différentes espèces, représentées par des couleurs. Les plus connues sont : le noir, le rouge, le blanc et le vert. Les dragons dorés n’existent presque exclusivement que dans les légendes, et les dragons de roche sont considérés comme éteints. Les statistiques et les compétences indiquées représentent les plus petites couleurs de dragons telles que le vert, le noir et le blanc ; le MJ devrait se sentir libre d’en ajouter pour représenter les plus grandes variétés. \nLes dragons dorés peuvent également prendre la forme d’humains ou d’autres créatures."
		},
		{
		  "Nom": "DRAUGIR",
		  "Menace": "Facile Simple",
			  "Type": "SPECTRE",
		  "Récompense": "65 couronnes",
		  "Armure": "30",
		  "Taille": "Taille humaine",
		  "Poids": "Selon l’équipement porté",
			"Environnement": ["Champs de bataille","Cimetière","Ruines"],
		  "Intelligence": "Consumé par ses émotions",
		  "Organisation": "De une à plusieurs dizaines, parfois menés par un draug",
		  "Note": ""
		},
		{
		  "Nom": "DRAUGR",
			  "Type": "SPECTRE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1800 couronnes",
		  "Armure": "30",
		  "Taille": "Jusqu’à 6 m",
		  "Poids": "Environ 1000 kg",
			"Environnement": ["Champs de bataille","Cimetière","Ruines"],
		  "Intelligence": "Aussi intelligent qu’il l’était en vie, souvent fou",
		  "Organisation": "Solitaire, souvent avec le draugir",
		  "Note": ""
		},
		{
		  "Nom": "DRYADE",
			  "Type": "VESTIGE",
		  "Menace": "Moyen Simple",
		  "Récompense": "350 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
			"Environnement": ["Forêts"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire, ou en bandes de 2 à 5",
		  "Note": "Les statistiques et les compétences représentées ici concernent les dryades de sang pur. Les dryades transformées sont susceptibles d’être légèrement moins puissantes, à discrétion du MJ."
		},
		{
		  "Nom": "ELEMENTAIRE FEU (fan)",
			  "Type": "ÉLÉMENTAIRE",
		  "Menace": "Difficile Complexe",
		  "Récompense": "1350 couronnes",
		  "Armure": "15",
		  "Taille": "Jusqu’à 2,5 m",
		  "Poids": "Jusqu’à 1000 kg",
			"Environnement": ["Invocation"],
		  "Intelligence": "Capable de pensées simples",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "ELEMENTAIRE GLACE (fan)",
			  "Type": "ÉLÉMENTAIRE",
		  "Menace": "Difficile Complexe",
		  "Récompense": "1350 couronnes",
		  "Armure": "25",
		  "Taille": "Jusqu’à 2,5 m",
		  "Poids": "Jusqu’à 1000 kg",
			"Environnement": ["Invocation"],
		  "Intelligence": "Capable de pensées simples",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "ELEMENTAIRE TERRE (fan)",
			  "Type": "ÉLÉMENTAIRE",
		  "Difficile": "Simple Récompense",
		  "1200 couronnes": "Armure",
		  "Taille": "Jusqu’à 2,5 m",
		  "Poids": "Jusqu’à 1000 kg",
			"Environnement": ["Invocation"],
		  "Intelligence": "Capable de pensées simples",
		  "Organisation": "Solitaire",
		  "Caract": {
			"INT": "1",
			"RÉF": "10",
			"DEX": "7",
			"COR": "12",
			"VIT": "2",
			"EMP": "1",
			"TECH": "1",
			"VOL": "5",
			"CHA": "0",
			"ETOU": "8",
			"COU": "6",
			"SAUT": "1",
			"END": "-",
			"ENC": "120",
			"REC": "8",
			"PS": "80",
			"VIG": "0"
		  },
		  "Note": ""
		},
		{
		  "Nom": "FLEDRE",
			  "Type": "VAMPIRE",
		  "Menace": "Moyen Simple",
		  "Récompense": "500 couronnes",
		  "Armure": "5",
		  "Taille": "Jusqu’à 2,5 m",
		  "Poids": "Jusqu’à 125 kg",
			"Environnement": ["Ruines","Grotte","Egouts"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire, parfois par 2 ou 3",
		  "Note": ""
		},
		{
		  "Nom": "GARGOUILLE",
			  "Type": "ÉLÉMENTAIRE",
		  "Menace": "Moyen Difficile",
		  "Récompense": "900 couronnes",
		  "Armure": "15",
		  "Taille": "Environ 1,75 m",
		  "Poids": "Environ 750 kg",
			"Environnement": ["Invocation"],
		  "Intelligence": "Incapable de réfléchir",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "HARPIE (fan)",
			  "Type": "HYBRIDE",
		  "Menace": "Facile Complexe",
		  "Récompense": "20 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,25 m, voûté",
		  "Poids": "Environ 65 kg",
			"Environnement": ["Ruines","Montagnes"],
		 "Intelligence": "Aussi intelligent qu’un humain stupide",
		  "Organisation": "Groupes de 5 à 20",
		   "Note": "Comme les pies, les harpies sont très attirées par les objets brillants. Leurs nids sont susceptibles de contenir divers objets métalliques comme des bijoux, des pièces de monnaie, ou même parfois des armes et des armures volées."
		},
		{
		  "Nom": "LESHEN (fan)",
			  "Type": "VESTIGE",
		  "Menace": "Fort Difficile",
		  "Récompense": "1750 couronnes",
		  "Armure": "5",
		  "Taille": "Environ 4 m",
		  "Poids": "Environ 250 kg",
			"Environnement": ["Forêts"],
		  "Intelligence": "Peut-être plus intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "MANTICORE (fan)",
			  "Type": "HYBRIDE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "750 couronnes",
		  "Armure": "8",
		  "Taille": "1,5 m au garrot",
		  "Poids": "Environ 550 kg",
				"Environnement": ["Montagnes","Plaines","Déserts"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
			"Note": ""
		},
		{
		  "Nom": "NAÏADE",
			  "Type": "VESTIGE",
		  "Menace": "Facile Difficile",
		  "Récompense": "250 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
				"Environnement": ["Forêts","Marin"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire ou en groupes de 2 ou 3",
		  "Note": ""
		},
		{
		  "Nom": "NAUCORE",
			  "Type": "INSECTOÏDE",
		  "Menace": "Facile Simple",
		  "Récompense": "30 couronnes",
		  "Armure": "10",
		  "Taille": "Environ 2 m",
		  "Poids": "Environ 90 kg",
				"Environnement": ["Marin"],
		  "Intelligence": "Aussi intelligent qu’un poisson",
		  "Organisation": "Solitaire, parfois par 2 ou 3",
		  "Note": ""
		},
		{
		  "Nom": "NEREIDE",
			  "Type": "VESTIGE",
		  "Menace": "Moyen Difficile",
		  "Récompense": "550 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine normale",
		  "Poids": "Poids humain normal",
				"Environnement": ["Marin"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire, parfois en groupes de 2 ou 3",
		  "Note": "Compagnon = Bongare"
		},
		{
		  "Nom": "Bongare",
			  "Type": "BÊTE",
		  "Menace": "Moyen Difficile",
		  "Récompense": "550 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine normale",
		  "Poids": "Poids humain normal",
				"Environnement": ["Marin"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire, parfois en groupes de 2 ou 3",
			"Note": "Compagnon de NEREIDE"
		},
		{
		  "Nom": "OGRE",
			  "Type": "OGROÏDE",
		  "Menace": "Moyen Simple",
		  "Récompense": "250 couronnes",
		  "Armure": "10",
		  "Taille": "Environ 2 m",
		  "Poids": "Environ 125 kg",
					"Environnement": ["Montagnes","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un humain stupide",
		  "Organisation": "Bande de guerriers de 3 à 6.<br>Jusqu’à 50 en communauté.",
			"Note": "Les ogres sont une race intelligente. Bien que stupides et violents, ils ont beaucoup plus de points communs avec les humains et les races anciennes que la plupart des monstres que les sorceleurs peuvent rencontrer."
		},
		{
		  "Nom": "PESTA (fan)",
			  "Type": "SPECTRE",
		  "Menace": "Fort Complexe",
		  "Récompense": "1000 couronnes",
		  "Armure": "0",
		  "Taille": "Taille humaine",
		  "Poids": "Intangible",
					"Environnement": ["Ville"],
		  "Intelligence": "Consumé par l’amertume ou la colère",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "PHENIX (fan)",
		  "Menace": "Fort Complexe",
			  "Type": "DRACONIDE",
		  "Récompense": "1000 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,75 m",
		  "Poids": "Environ 180 kg",
				"Environnement": ["Montagnes","Plaines","Déserts"],
		  "Intelligence": "Aussi intelligent qu’un humain stupide",
		  "Organisation": "Solitaire",
		 "Note": ""
		},
		{
		  "Nom": "PUTRÉFACTEUR (fan)",
			  "Type": "NÉCROPHAGE",
		  "Menace": "Facile Difficile",
		  "Récompense": "30 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,5 m",
		  "Poids": "Environ 80 kg",
				"Environnement": ["Champs de bataille","Cimetière"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Groupes de 3 à 6",
		  "Note": ""
		},
		{
		  "Nom": "SHAELMAAR (fan)",
		  "Menace": "Moyen Complexe",
			  "Type": "VESTIGE",
		  "Récompense": "600 couronnes",
		  "Armure": "25",
		  "Taille": "Environ 3 m",
		  "Poids": "Environ 800 kg",
				"Environnement": ["Grotte","Montagnes"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "STRYGE",
		  "Menace": "Moyen Difficile",
			  "Type": "CRÉATURE MAUDITE",
		  "Récompense": "650 couronnes",
		  "Armure": "5",
		  "Taille": "Environ 1,25 m au garrot",
		  "Poids": "Environ 125 kg",
				"Environnement": ["Ruines"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "SUCCUBE",
		  "Menace": "Moyen Complexe",
			  "Type": "HYBRIDE",
		  "Récompense": "650 couronnes",
		  "Armure": "5",
		  "Taille": "Taille humaine",
		  "Poids": "Poids humain",
				"Environnement": ["Ville"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire",
		  "Note": "Le pendant masculin de la succube est l’incube. Il est identique à la succube à tous égards, sauf en ce qui concerne son apparence."
		},
		{
		  "Nom": "SYLVAIN",
			  "Type": "VESTIGE",
		  "Menace": "Moyen Simple",
		  "Récompense": "500 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 3 m",
		  "Poids": "Jusqu’à 200 kg",
					"Environnement": ["Ruines","Forêts"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Solitaire, parfois en petites communautés",
		  "Note": "Les sylvains sont une race intelligence et généralement placide, et ont beaucoup plus de points communs avec les humains et les races anciennes que la plupart des monstres que les sorceleurs peuvent rencontrer. On les trouve souvent en interaction (semi-)pacifique avec des communautés humains dans les régions les plus isolées."
		},
		{
		  "Nom": "TSCHART",
			  "Type": "VESTIGE",
		  "Menace": "Difficile Complexe",
		  "Récompense": "1250 couronnes",
		  "Armure": "8",
		  "Taille": "2 m au garrot",
		  "Poids": "Environ 800 kg",
					"Environnement": ["Plaines","Forêts"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "VAMPIRE SUPERIEUR (fan)",
			  "Type": "VAMPIRE",
		  "Menace": "Fort Difficile",
		  "Récompense": "2000+ couronnes",
		  "Armure": "20",
		  "Taille": "Taille humaine normale",
		  "Poids": "Poids humain normal",
				"Environnement": ["Ville","Partout"],
		  "Intelligence": "Bien plus intelligent qu’un humain",
		  "Organisation": "Solitaire",
		 "Note": ""
		},
		{
		  "Nom": "VODIANOÏ",
			  "Type": "OGROÏDE",
		  "Menace": "Facile Complexe",
		  "Récompense": "35 couronnes",
		  "Armure": "4",
		  "Taille": "Environ 1,75 m",
		  "Poids": "Jusqu’à 75 kg",
				"Environnement": ["Marin"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Groupes de 4 à 10, communautés",
		  "Note": "Les vodianoï sont une espèce intelligente et ont beaucoup plus de points communs avec les humains et les races anciennes que la plupart des monstres que les sorceleurs peuvent rencontrer.  Souvent dirigé par un chef."
		},
		{
		  "Nom": "PRÊTRE VODIANOÏ",
			  "Type": "OGROÏDE",
		  "Menace": "Facile Complexe",
		  "Récompense": "35 couronnes",
		  "Armure": "4",
		  "Taille": "Environ 1,75 m",
		  "Poids": "Jusqu’à 75 kg",
				"Environnement": ["Marin"],
		  "Intelligence": "Aussi intelligent qu’un humain",
		  "Organisation": "Groupes de 4 à 10, communautés",
		  "Note": "Souvent, un groupe de vodianoï est dirigé par un prêtre. Tant que celui-ci est vivant, tous les vodianoï de son groupe ont un bonus de +4 en Courage."
		},
		{
		  "Nom": "ZEUGLE",
		  "Menace": "Fort Simple",
			  "Type": "INSECTOÏDE",
		  "Récompense": "1250 couronnes",
		  "Armure": "10",
		  "Taille": "Environ 6 m",
		  "Poids": "Jusqu’à 500 kg",
				"Environnement": ["Egouts","Marécages"],
		  "Intelligence": "Aussi intelligent qu’un poisson",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
		  "Nom": "ANOPHELI",
			  "Type": "OGROÏDE",
		  "Menace": "Facile Simple",
		  "Récompense": "40 couronnes",
		  "Armure": "3",
		  "Taille": "1,25 - 1,5 m voûté",
		  "Poids": "Environ 65 kg, jusqu’à 100 kg si bien nourri",
				"Environnement": ["Grotte","Marécages"],
		  "Intelligence": "Nourri, comme un humain stupide (comme un poisson quand il a faim)",
		  "Organisation": "Entre 1 et 3 en itinérance (jusqu’à 12 dans un nid)",
		  "Note": ""
		},
		{
		  "Nom": "BERBEROKA",
			  "Type": "HYBRIDE",
		  "Menace": "Facile Simple",
		  "Récompense": "45 couronnes",
		  "Armure": "5",
		  "Taille": "Environ 1 m au garrot",
		  "Poids": "Environ 95 kg",
				"Environnement": ["Marécages"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Meutes de 3 à 6",
		  "Note": ""
		},
		{
		  "Nom": "BUKUVAK",
			  "Type": "DRACONIDE",
		  "Menace": "Moyen Simple",
		  "Récompense": "150 couronnes",
		  "Armure": "5",
		  "Taille": "1 m au garrot",
		  "Poids": "Environ 175 kg",
				"Environnement": ["Marin"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire, parfois avec des noyeurs",
		  "Note": ""
		},
		{
		  "Nom": "GUVORAG",
			  "Type": "INSECTOÏDE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "450 couronnes",
		  "Armure": "10",
		  "Taille": "Environ 3 m",
		  "Poids": "Environ 250 kg",
					"Environnement": ["Ruines","Forêts"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
			"Note": ""
		},
		{
		  "Nom": "PRETA",
			  "Type": "CRÉATURE MAUDITE",
		  "Menace": "Facile Difficile",
		  "Récompense": "50 couronnes",
		  "Armure": "0",
		  "Taille": "Environ 1,25 m, voûté",
		  "Poids": "Environ 50 kg",
				"Environnement": ["Partout"],
		  "Intelligence": "Consumé par la faim",
		  "Organisation": "Groupes de 3 à 6",
		  "Note": ""
		},
		{
		  "Nom": "UKTENA",
			  "Type": "HYBRIDE",
		  "Menace": "Moyen Complexe",
		  "Récompense": "650 couronnes",
		  "Armure": "8",
		  "Taille": "Longueur d’environ 10 m",
		  "Poids": "Jusqu’à 750 kg",
					"Environnement": ["Montagnes","Forêts","Grotte"],
		  "Intelligence": "Aussi intelligent qu’un chien",
		  "Organisation": "Solitaire",
		  "Note": ""
		},
		{
    "Nom": "BRUMELIN",
    "Menace": "Moyen Difficile",
		  "Type": "NÉCROPHAGE",
    "Récompense": "800 couronnes",
    "Armure": "0",
    "Taille": "Environ 2 m",
    "Poids": "Environ 75 kg",
    "Environnement": ["Grotte","Marécages"],
    "Intelligence": "Sauvage",
    "Organisation": "Solitaire",
   "Note": ""
  },
	  {
		"Nom": "BULLVORE",
			  "Type": "NÉCROPHAGE",
		"Menace": "Moyen Complexe",
		"Récompense": "500 couronnes",
		"Armure": "8",
		"Taille": "3.5 m",
		"Poids": "500 kg",
		"Environnement": ["Grotte"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "PUTRÉFACTEURS",
			  "Type": "NÉCROPHAGE",
		"Menace": "Faible Simple",
		"Récompense": "10 couronnes",
		"Armure": "0",
		"Taille": "2 m",
		"Poids": "80 kg",
		"Environnement": ["Grotte","Champs de bataille"],
		"Intelligence": "Sauvage",
		"Organisation": "Groupes de 4 à 6 individus",
		"Note": ""
	  },
	  {
		"Nom": "BARGHEST",
			  "Type": "SPECTRE",
		"Menace": "Faible Complexe",
		"Récompense": "30 couronnes",
		"Armure": "0",
		"Taille": "Environ 1 m",
		"Poids": "Environ 40 kg",
		"Environnement": ["Ville"],
		"Intelligence": "Sauvage",
		"Organisation": "Meutes de 3 à 5 individus",
		"Note": ""
	  },
	  {
		"Nom": "BLÊME",
			  "Type": "SPECTRE",
		"Menace": "Fort Difficile",
		"Récompense": "1 500 couronnes",
		"Armure": "0",
		"Taille": "3 m",
		"Poids": "Intangible",
		"Environnement": ["Ville"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "PESTA",
			  "Type": "SPECTRE",
		"Menace": "Fort Difficile",
		"Récompense": "900 couronnes",
		"Armure": "0",
		"Taille": "1.75 m",
		"Poids": "Intangible",
		"Environnement": ["Ville"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": "<b>Horde de rats de la peste</b><br>Points de santé : 10 Esquive (base) : 16 Vitesse : 5 Attaque (base) : 14<br>Quand la horde de rats effectue une attaque, elle tente de noyer la cible sous le nombre et de lui infliger des morsures. La cible doit réaliser un jet d’Esquive/Évasion ou une tentative de repositionnement pour éviter l’attaque. Si la horde de rats réussit son attaque, la cible subit 2d6 dégâts sur tout le corps et a 50 % de chance de tomber malade."
	  },
	  {
		"Nom": "OURS",
			  "Type": "BÊTE",
		"Menace": "Moyen Simple",
		"Récompense": "450 couronnes",
		"Armure": "10",
		"Taille": "1.75 m",
		"Poids": "600 kg",
		"Environnement": ["Forêts"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par deux",
		"Note": ""
	  },
	  {
		"Nom": "OURS GRIS",
			  "Type": "BÊTE",
		"Menace": "Moyen Simple",
		"Récompense": "450 couronnes",
		"Armure": "14",
		"Taille": "1.75 m",
		"Poids": "600 kg",
		"Environnement": ["Forêts","Skellige"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par deux",
		"Note": "Dans les profondeurs des forêts du Continent et sur les îles de Skellige, les ours sont plus massifs et effrayants que les tas de muscles déjà menaçants qui rôdent à la lisière des bois. Ces ours gris sont agressifs et possèdent un instinct territorial exacerbé. Très souvent, ils doivent se battre avec des monstres issus de la Conjonction pour sécuriser leur domaine.<br>Ces ours gris ont une armure améliorée avec un Pouvoir d’arrêt de 14, ainsi qu’une résistance aux attaques perforantes, tranchantes et contondantes. Enfin, la base de leurs attaques s’élève à 17, à l’exception de la capacité Frappe brutale, qui a une base de 14."
	  },
	  {
		"Nom": "PANTHÈRE",
			  "Type": "BÊTE",
		"Menace": "Moyen Simple",
		"Récompense": "20 couronnes",
		"Armure": "0",
		"Taille": "0.75 m",
		"Poids": "78 kg",
		"Environnement": ["Forêts"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par deux",
		"Note": ""
	  },
	  {
		"Nom": "GRAND CHAT",
			  "Type": "BÊTE",
		"Menace": "Moyen Simple",
		"Récompense": "20 couronnes",
		"Armure": "5",
		"Taille": "0.75 m",
		"Poids": "78 kg",
		"Environnement": ["Nilfgaard"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par deux",
		"Note": "On entend régulièrement des histoires concernant des félins plus gros que des panthères qui rôdent dans les forêts du sud de Nilfgaard. Ces prédateurs, qu’on appelle de manière très inspirée les grands chats, sont des chasseurs consommés connus pour tendre des embuscades aux petits groupes de marchands et désarçonner les chevaliers en un bond.<br>Ces grands chats ont une armure améliorée avec un Pouvoir d’arrêt de 5. Leur attaque de griffe inflige 3d6+2 dégâts et est équilibrée, tandis que la morsure, susceptible de provoquer un saignement (50 %) inflige 5d6+4 dégâts. La base pour ces attaques s’élève à 17."
	  },
	  {
		"Nom": "SANGLIER",
			  "Type": "BÊTE",
		"Menace": "Faible Difficile",
		"Récompense": "10 couronnes",
		"Armure": "5",
		"Taille": "1 m",
		"Poids": "90 kg",
		"Environnement": ["Forêts","Plaines"],
		"Intelligence": "Sauvage",
		"Organisation": "Compagnie de 2 à 6 individus",
		"Note": ""
	  },
	  {
		"Nom": "SANGLIER DE GUERRE",
			  "Type": "BÊTE",
		"Menace": "Faible Difficile",
		"Récompense": "10 couronnes",
		"Armure": "10",
		"Taille": "1 m",
		"Poids": "90 kg",
		"Environnement": ["Skellige"],
		"Intelligence": "Sauvage",
		"Organisation": "Compagnie de 2 à 6 individus",
		"Note": "Certaines ethnies, en particulier à Skellige, portent un amour immodéré aux sangliers de guerre. Ces animaux de combat choisis parmi les individus les plus robustes sont dressés pour devenir de véritables machines à tuer. On les envoie sur le champ de bataille pour désorganiser les rangs adverses et saper le moral de l’ennemi.<br>Ces sangliers de guerre ont une armure améliorée avec un Pouvoir d’arrêt de 10. De plus, son coup de défense inflige 4d6 dégâts et sa capacité Charge furieuse 6d6. La base pour ces deux attaques s’élève à 15."
	  },
	  {
		"Nom": "COUVIN",
			  "Type": "CRÉATURE MAUDITE",
		"Menace": "Moyen Complexe",
		"Récompense": "600 couronnes",
		"Armure": "0",
		"Taille": "0.3 m",
		"Poids": "3.5 kg",
		"Environnement": ["Ville"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par paire",
		"Note": "Transformation : Sommeillard ou Transformation : Forme de combat"
	  },
	  {
		"Nom": "COUVIN FORME DE COMBAT",
			  "Type": "CRÉATURE MAUDITE",
		"Menace": "Moyen Complexe",
		"Récompense": "600 couronnes",
		"Armure": "0",
		"Taille": "0.3 m",
		"Poids": "3.5 kg",
		"Environnement": ["Ville"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par paire",
		"Note": "Après avoir bu le sang d’une cible ou lorsqu’il se sent menacé, le couvin consacre un tour complet à se métamorphoser. Quand il est sous sa forme de combat, le couvin gagne +2 en RÉF, DEX et VIT et +3 en COR. Il peut également attaquer avec ses griffes et utiliser une action pour couvrir son corps de piquants. Tant que les épines sont sorties, les adversaires qui réussissent à agripper le couvin subissent 2d6 dégâts au torse. En outre, les armes qui frappent le couvin subissent 1 point de dégâts d’ablation. Si le couvin est étourdi, les piquants se rétractent. Une fois qu’il est transformé, on peut obliger le couvin à retrouver sa forme d’origine. Il faut utiliser le signe d’Axii ou le sort Manipulation de l’esprit et réussir un jet d’Incantation (SD 18). Toutefois, si le couvin est attaqué après un lancement de sort réussi, il reprend immédiatement sa forme de combat et le SD du jet d’Incantation passe à 25 au lieu de 18."
	  },
	  {
		"Nom": "SOMMEILLARD",
			  "Type": "CRÉATURE MAUDITE",
		"Menace": "Moyen Complexe",
		"Récompense": "600 couronnes",
		"Armure": "0",
		"Taille": "0.3 m",
		"Poids": "3.5 kg",
		"Environnement": ["Ville"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par paire",
		"Note": "Un parent du couvin peut accomplir le rituel de baptême elfique d’Aymm Rhoin pour le transformer en sommeillard. Il doit creuser une tombe pour le couvin et prononcer une formule spécifique. Le sommeillard quitte le corps enseveli un jour et une nuit plus tard et devient un esprit gardien amical qui est attaché à la maison familiale. Une fois transformé en sommeillard, le couvin devient incorporel et peut se déplacer de 8 mètres à l’horizontale ou à la verticale lors de son action de mouvement. Tant qu’il flotte dans les airs, le sommeillard doit se repositionner pour se défendre contre les attaques. En outre, il ne peut plus adopter de forme de combat ou utiliser les capacités Drain de force vitale et Drain de sang."
	  },
	  {
		"Nom": "ÉKINOPPYRE BRUNE",
			  "Type": "CRÉATURE MAUDITE",
		"Menace": "Faible Difficile",
		"Récompense": "30 couronnes",
		"Armure": "0",
		"Taille": "2.5 m",
		"Poids": "68 kg",
		"Environnement": ["Champs de bataille","Cimetière"],
		"Intelligence": "Sauvage",
		"Organisation": "Entre 3 et 5 plants",
		"Note": "L’ékinoppyre brune est la plus faible de toutes."
	  },
	  {
		"Nom": "ÉKINOPPYRE VERTE",
			  "Type": "CRÉATURE MAUDITE",
		"Menace": "Faible Difficile",
		"Récompense": "30 couronnes",
		"Armure": "0",
		"Taille": "2.5 m",
		"Poids": "68 kg",
		"Environnement": ["Champs de bataille","Cimetière"],
		"Intelligence": "Sauvage",
		"Organisation": "Entre 3 et 5 plants",
		"Note": "L’ékinoppyre brune est la plus faible de toutes."
	  },
	  {
		"Nom": "ÉKINOPPYRE VIOLETTE",
			  "Type": "CRÉATURE MAUDITE",
		"Menace": "Faible Difficile",
		"Récompense": "30 couronnes",
		"Armure": "0",
		"Taille": "2.5 m",
		"Poids": "68 kg",
		"Environnement": ["Champs de bataille","Cimetière"],
		"Intelligence": "Sauvage",
		"Organisation": "Entre 3 et 5 plants",
		"Note": "L’ékinoppyre brune est la plus faible de toutes."
	  },
	  {
		"Nom": "VENDIGO",
			  "Type": "CRÉATURE MAUDITE",
		"Menace": "Fort Difficile",
		"Récompense": "1 500 couronnes",
		"Armure": "10",
		"Taille": "3.5 m",
		"Poids": "110 kg",
		"Environnement": ["Montagnes"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "HARPIE",
			  "Type": "HYBRIDE",
		"Menace": "Faible Simple",
		"Récompense": "15 couronnes",
		"Armure": "0",
		"Taille": "1.5 m",
		"Poids": "60 kg",
		"Environnement": ["Montagnes","Marin"],
		"Intelligence": "Sauvage",
		"Organisation": "Nuée de 4 à 8 individus",
		"Note": "Vous pouvez tomber sur une nuée de harpies menée par une célénos ou une modeste colonie de célénos qui a élu domicile non loin des habitations. Les célénos sont des êtres intelligents qui ont un bonus de +2 en Intelligence. Elles interagissent rarement avec les autres créatures, mais disposent d’une base 13 en Résistance à la contrainte."
	  },
	  {
		"Nom": "HARPIE CÉLÉNOS",
			  "Type": "HYBRIDE",
		"Menace": "Faible Simple",
		"Récompense": "15 couronnes",
		"Armure": "0",
		"Taille": "1.5 m",
		"Poids": "60 kg",
		"Environnement": ["Montagnes","Marin"],
		"Intelligence": "Sauvage",
		"Organisation": "Nuée de 4 à 8 individus",
		"Note": "Vous pouvez tomber sur une nuée de harpies menée par une célénos ou une modeste colonie de célénos qui a élu domicile non loin des habitations. Les célénos sont des êtres intelligents qui ont un bonus de +2 en Intelligence. Elles interagissent rarement avec les autres créatures, mais disposent d’une base 13 en Résistance à la contrainte.<br>Une harpie célénos a aussi le pouvoir de voler les rêves des gens pour les emprisonner dans des cristaux. Quand elle se trouve à 4 mètres d’une personne endormie, elle peut utiliser son tour complet pour dérober les songes de sa victime, puis les infuser dans une gemme pour fabriquer un cristal de rêve. Chaque cristal contient un seul rêve, que l’on peut visionner à l’aide d’un mégascope en réussissant un jet d’Exercice de la magie (SD 17) ou d’un projecteur de rêve, qu’on retrouve dans les nids de harpie célénos ou à proximité. Bien que les harpies n’aient pas construit ces appareils, elles ont appris à s’en servir. Un cristal de rêve peut aussi tenir lieu de Focus avec une valeur de 1. Si le songe est particulièrement puissant ou provient d’une créature magique, la valeur de Focus du cristal passe à 3. Lorsque vous tuez une harpie célénos, ajoutez 1d6/2 essence cristallisée et 1d6/2 cristal de rêve."
	  },
	  {
		"Nom": "MANTICORE",
			  "Type": "HYBRIDE",
		"Menace": "Fort Complexe",
		"Récompense": "1 600 couronnes",
		"Armure": "15",
		"Taille": "1.75 m",
		"Poids": "204 kg",
		"Environnement": ["Montagnes","Forêts"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par paire",
		"Note": ""
	  },
	  {
		"Nom": "SUCCUBE",
			  "Type": "HYBRIDE",
		"Menace": "Moyen Simple",
		"Récompense": "400 couronnes",
		"Armure": "0",
		"Taille": "1.8 m",
		"Poids": "80 kg",
		"Environnement": ["Ville"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": "Les succubes et les incubes sont des hybrides avec lesquels on peut facilement négocier. Ce sont des créatures douées d’intelligence, soumises aux mêmes désirs et pulsions que les humains. Cela étant dit, j’ai connu de nombreux sorceleurs qui ont été victimes d’incidents “excitants” lors de leurs tractations avec des succubes et des incubes."
	  },
	  {
		"Nom": "BARBEGAZI",
			  "Type": "INSECTOÏDE",
		"Menace": "Faible Complexe",
		"Récompense": "15 couronnes",
		"Armure": "3",
		"Taille": "1 m",
		"Poids": "25 kg",
		"Environnement": ["Montagnes"],
		"Intelligence": "Sauvage",
		"Organisation": "Colonies de 4 à 10 individus",
		"Note": ""
	  },
	  {
		"Nom": "ÉPOUVANTEUR",
			  "Type": "INSECTOÏDE",
		"Menace": "Fort Difficile",
		"Récompense": "2 000 couronnes",
		"Armure": "30",
		"Taille": "4.5 m",
		"Poids": "3000 kg",
		"Environnement": ["Montagnes","Déserts"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "SCOLOPENDROMORPHE",
		"Menace": "Faible Complexe",
			  "Type": "INSECTOÏDE",
		"Récompense": "20 couronnes",
		"Armure": "8(3)",
		"Taille": "4.5 m",
		"Poids": "200 kg",
		"Environnement": ["Forêts","Plaines"],
		"Intelligence": "Sauvage",
		"Organisation": "Groupes de 3 à 6 individus",
		"Note": ""
	  },
	  {
		"Nom": "ÉLÉMENTAIRE DE FEU",
			  "Type": "ÉLÉMENTAIRE",
		"Menace": "Fort Complexe",
		"Récompense": "1 600 couronnes",
		"Armure": "15",
		"Taille": "2.5 m",
		"Poids": "2 700 kg",
		"Environnement": ["Invocation"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "ÉLÉMENTAIRE DE GLACE",
			  "Type": "ÉLÉMENTAIRE",
		"Menace": "Fort Complexe",
		"Récompense": "1 600 couronnes",
		"Armure": "20",
		"Taille": "2.5 m",
		"Poids": "2 700 kg",
		"Environnement": ["Invocation"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "ÉLÉMENTAIRE DE TERRE",
			  "Type": "ÉLÉMENTAIRE",
		"Menace": "Fort Complexe",
		"Récompense": "1 600 couronnes",
		"Armure": "20",
		"Taille": "2.5 m",
		"Poids": "2 700 kg",
		"Environnement": ["Invocation"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "CÉLICOLE",
			  "Type": "VESTIGE",
		"Menace": "Faible Simple",
		"Récompense": "20 couronnes",
		"Armure": "0",
		"Taille": "1 m",
		"Poids": "22 kg",
		"Environnement": ["Ville"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire ou par paire",
		"Note": ""
	  },
	  {
		"Nom": "LESHEN",
			  "Type": "VESTIGE",
		"Menace": "Fort Difficile",
		"Récompense": "1 500 couronnes",
		"Armure": "16",
		"Taille": "2.5 m",
		"Poids": "136 kg",
		"Environnement": ["Forêts"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "SHAELMAAR",
			  "Type": "VESTIGE",
		"Menace": "Moyen Complexe",
		"Récompense": "500 couronnes",
		"Armure": "20 (0)",
		"Taille": "2 m",
		"Poids": "2 000 kg",
		"Environnement": ["Montagnes","Grotte"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "CYCLOPE",
			  "Type": "OGROÏDE",
		"Menace": "Fort Simple",
		"Récompense": "1 200 couronnes",
		"Armure": "25",
		"Taille": "6 m",
		"Poids": "3 000 kg",
		"Environnement": ["Montagnes","Plaines"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire ou par paire",
		"Note": ""
	  },
	  {
		"Nom": "FRAPPEUR",
			  "Type": "OGROÏDE",
		"Menace": "Faible Simple",
		"Récompense": "25 couronnes",
		"Armure": "3",
		"Taille": "2.5 m",
		"Poids": "450 kg",
		"Environnement": ["Montagnes","Grotte"],
		"Intelligence": "Pensant",
		"Organisation": "Groupes de 2 à 6 individus",
		"Note": "Je ne compte pas le nombre de fois où mes frères et moi avons été appelés à Mahakam pour nous occuper de frappeurs ou de kobolds. En général, les ogroïdes sont plus une nuisance qu’une véritable menace. Ils volent des outils, s’amusent à effrayer les mineurs et sabotent les passerelles. Certes, ces plaisanteries peuvent devenir dangereuses, mais rien de comparable avec la violence et la soif de sang d’un shaelmaar ou d’un ogre. Il y a quelques années, j’ai passé trois jours avec Vaz dans les profondeurs des mines de Mahakam, où nous naviguions entre les fils de détente installés entre les parois et les fausses dalles, à la recherche d’une bande de frappeurs qui tendait des embuscades aux mineurs pour dérober leur eau-de-vie. Je dois admettre que notre patience était presque à bout au moment où nous les avons trouvés. Les négociations ont failli tourner au vinaigre quand les créatures velues se sont mises à nous lancer des pierres. Heureusement, la raison l’a emporté, et un Axii bienvenu les a rendus ouverts à la discussion."
	  },
	  {
		"Nom": "TROLL",
			  "Type": "OGROÏDE",
		"Menace": "Moyen Simple",
		"Récompense": "800 couronnes",
		"Armure": "12",
		"Taille": "2.5 m",
		"Poids": "500 kg",
		"Environnement": ["Partout"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire ou par paire",
		"Note": "Quand vous êtes face à un troll, vous devez garder à l’esprit que, malgré ses similitudes avec les humains, il appartient à une autre espèce. La plupart d’entre eux considèrent les humains, les elfes et les races douées de raison comme des compagnons et de la nourriture. Lorsque vous entamez les négociations, il faut lui montrer que, même si vous êtes prêt à marchander, il ne doit pas vous prendre à la légère. En général, un peu de vodka ou de viande fraîche suffisent à se mettre un troll dans la poche, toutefois, à l’image des humains, certains individus préfèreront vous tuer pour ensuite piller votre cadavre. Plusieurs fois, il m’a suffi de dégainer mon épée d’argent pour prouver à un troll chicanier qu’il ne fallait pas plaisanter avec moi, encore que mes yeux de chat et mon médaillon en argent aient pu aussi jouer en ma faveur. Si vous n’êtes pas un sorceleur, je vous conseille de vous rendre à la table des négociations accompagné d’un groupe de guerriers ou équipé d’une arme impressionnante."
	  },
	  {
		"Nom": "COCKATRIX",
			  "Type": "DRACONIDE",
		"Menace": "Moyen Simple",
		"Récompense": "800 couronnes",
		"Armure": "8",
		"Taille": "2 m",
		"Poids": "800 kg",
		"Environnement": ["Montagnes","Grotte"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par paire",
		"Note": "Si un jour on vous engage pour tuer une cockatrix, enquêtez sur ce qui se cache derrière ce contrat. Comme les ours, les cockatrix occupent un territoire délimité et ne s’aventurent jamais au-delà pour chasser. Tant que vous ne pénétrez pas dans cette zone, le monstre vous laisse tranquille. Les problèmes surviennent lorsqu’une route commerciale traverse ce territoire, sans oublier les employeurs qui voulaient simplement mettre la main sur le plumage chatoyant de la bête."
	  },
	  {
		"Nom": "PHÉNIX",
			  "Type": "DRACONIDE",
		"Menace": "Moyen Difficile",
		"Récompense": "1 200 couronnes",
		"Armure": "10",
		"Taille": "3 m",
		"Poids": "550 kg",
		"Environnement": ["Montagnes"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire ou par paire",
		"Note": ""
	  },
	  {
		"Nom": "SLYZARD",
			  "Type": "DRACONIDE",
		"Menace": "Fort Complexe",
		"Récompense": "1 500 couronnes",
		"Armure": "16",
		"Taille": "3 m",
		"Poids": "950 kg",
		"Environnement": ["Montagnes"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par paire",
		"Note": ""
	  },
	  {
		"Nom": "BROUXE",
			  "Type": "VAMPIRE",
		"Menace": "Fort Difficile",
		"Récompense": "2 000 couronnes",
		"Armure": "10",
		"Taille": "1.75 m",
		"Poids": "90 kg",
		"Environnement": ["Ville"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": ""
	  },
	  {
		"Nom": "GARKAIN",
			  "Type": "VAMPIRE",
		"Menace": "Moyen Complexe",
		"Récompense": "700 couronnes",
		"Armure": "0",
		"Taille": "2.25 m",
		"Poids": "136 kg",
		"Environnement": ["Ville"],
		"Intelligence": "Sauvage",
		"Organisation": "Solitaire ou par paire",
		"Note": "Sans surprise, on a découvert que bon nombre de meurtres tristement célèbres avaient été perpétrés par des garkains qui opéraient dans des villes populeuses. Si vous remontez la piste d’assassinats sanglants, abominables, je vous conseille d’attendre l’aube pour mener l’enquête."
	  },
	  {
		"Nom": "PLUMEUR",
			  "Type": "VAMPIRE",
		"Menace": "Faible Simple",
		"Récompense": "15 couronnes",
		"Armure": "0",
		"Taille": "1 m",
		"Poids": "4.5 kg",
		"Environnement": ["Forêts","Marécages"],
		"Intelligence": "Sauvage",
		"Organisation": "Nuées de 6 à 12 individus",
		"Note": "Les plumeurs sont les vampires les plus faibles du Continent. Cela ne signifie pas pour autant qu’ils sont inoffensifs. Un jour, au cours de mes voyages, j’ai rencontré une aristocrate qui avait décidé d’en garder un dans sa ménagerie. Le plumeur en lui-même n’avait rien de terrifiant, il passait son temps à faire le tour de sa cage d’argent avec des battements d’ailes furieux. Par comparaison, la nuée qui fondit sur le manoir quatre nuits plus tard ne prêtait pas à rire."
	  },
	  {
		"Nom": "DRAGON VERT",
			  "Type": "DRACONIDE",
		"Menace": "Légendaire Complexe",
		"Récompense": "5 000 couronnes",
		"Armure": "25",
		"Taille": "5 m",
		"Poids": "300 kg",
		"Environnement": ["Forêts"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": "Les dragons verts sont les plus courants, mais aussi les plus petits, atteignant à peine les cinq mètres. Leurs écailles vertes tachetées leur permettent de se camoufler dans les bois qu’ils occupent, nichant près des sources chaudes. Comme les dragons verts possèdent une paire d’ailes en guise de membres antérieurs et une paire de pattes postérieures, ils sont plus à l’aise dans les airs ; néanmoins, ils se déplacent sur terre à une allure efficace quandles circonstances l’exigent. Pour ce qui est de ses moyens de défense, sa morsure s’accompagne d’un puissant venin auquel on ne connaît aucun remède alchimique. Souvent, c’est cette morsure qui signe l’arrêt de mort des fous qui le défient. Quand il est attaqué, le reptile commence en général par déverser un jet de vapeur brûlante qui repousse ses agresseurs ou les cuit dans leur armure. Certes, les dragons verts sont plutôt amicaux, mais ils deviennent violents lorsqu’ils se sentent menacés ou humiliés.<br>L’attaque de morsure du dragon vert gagne l’effet Poison (100 %) chaque fois qu’elle inflige des dégâts. Une créature empoisonnée subit 5 points de dégâts par round, qui ne sont pas absorbés par l’armure, et un malus de –3 sur toutes ses actions tant que dure l’empoisonnement. La potion de Loriot doré est sans effet contre le venin du dragon vert. Pour chasser les toxines, il faut accomplir un Rituel de purification ou réussir un jet de Résilience (SD 25)."
	  },
	  {
		"Nom": "DRAGON ROUGE",
			  "Type": "DRACONIDE",
		"Menace": "Légendaire Complexe",
		"Récompense": "5 000 couronnes",
		"Armure": "25",
		"Taille": "12 à 15 m",
		"Poids": "800 kg",
		"Environnement": ["Montagnes"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": "Les dragons rouges sont la terreur du Continent, pas tant à cause de leur tempérament – parfois orgueilleux et agressif – qu’en raison de leur souffle brûlant. En un clin d’oeil, ils vomissent un torrent de flammes ardentes qui fait fondre les rochers et les briques situés au coeur du déluge. Nombre de villes ont été réduites en cendre après le passage d’un dragon rouge. Ces reptiles abominables possèdent une carrure impressionnante – ils atteignent les douze ou quinze mètres de long –, des écailles rouge brique et un corps parsemé d’éperons osseux. Ils vivent au coeur des montagnes, qu’ils quittent pour se nourrir et collecter des trésors afin d’agrandir leur butin. En général, lorsque des villageois aperçoivent un dragon, celui-ci va soit se régaler de leurs chevaux, soit emporter des statues et autres biens de valeur. Ce comportement a valu une mauvaise réputation aux dragons rouges qui sont le reste du temps des partenaires de conversation charmants, amateurs de débats.<br>Le souffle enflammé d’un dragon rouge inflige 10d6 dégâts au lieu de 7d6. Quand l’attaque inflige des dégâts, l’armure de la cible subit un montant de dégâts d’ablation égal à la moitié des dégâts infligés par le souffle enflammé. Si la cible bloque avec son bouclier, celui-ci subit un montant de dégâts équivalent."
	  },
	  {
		"Nom": "DRAGON NOIR",
			  "Type": "DRACONIDE",
		"Menace": "Légendaire Complexe",
		"Récompense": "5 000 couronnes",
		"Armure": "25",
		"Taille": "6 m",
		"Poids": "400 kg",
		"Environnement": ["Nilfgaard"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": "Les dragons noirs sont une sous-espèce particulièrement rare, dont on trouve des traces dans les territoires du sud, près de Nilfgaard et de Gemmery. Il s’agit des reptiles les plus massifs, qui atteignent les quinze ou vingt mètres de long, pourvus d’immenses ailes et de quatre pattes robustes munies de griffes acérées. Le dragon noir doit son appellation à ses écailles qui varient du brun foncé au noir, réputées pour être aussi solides que l’acier mahakamien. D’ailleurs, on dit que partir en chasse sans s’équiper au minimum d’une baliste est pure folie, car tout autre projectile glisserait sur son épiderme, telles les gouttes de pluie sur le plumage d’un oiseau. Un dragon noir enragé est capable de déverser un jet d’acide brûlant produit par les glandes situées au niveau de sa mâchoire. Ce liquide caustique ronge les armures les plus résistantes qui soient et a tendance à faire fondre le terrain autour de la victime. Heureusement, les dragons sont des créatures paresseuses qui mettent du temps avant de s’énerver.<br>Un dragon noir possède des écailles impénétrables qui lui confèrent une résistance au perforant, au tranchant, au contondant, à l’étourdissement et au feu. Les armes qui possèdent perforation ou perforation améliorée sont sans effet contre son armure et ses résistances, et les dégâts d’ablation sont divisés par deux (minimum 1)."
	  },
	  {
		"Nom": "DRAGON BRUN",
			  "Type": "DRACONIDE",
		"Menace": "Légendaire Complexe",
		"Récompense": "5 000 couronnes",
		"Armure": "25",
		"Taille": "10 m",
		"Poids": "600 kg",
		"Environnement": ["Montagnes"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": "Les dragons bruns, qu’on appelle aussi dragons de roches, sont les moins connus de tous. À première vue, ils paraissent moins impressionnants que leurs congénères, ce qui explique peut-être cette méconnaissance. Leur corps élancé de dix mètres de long est pourvu de petites ailes qui épousent parfaitement leur silhouette une fois repliées. Leur tête irrégulière et caparaçonnée se perche sur une encolure courte, et leurs quatre pattes musculeuses se terminent par des griffes tranchantes et larges à la façon d’une pelle. Le dragon brun arbore des écailles à la teinte acajou, sauf le long de la colonne vertébrale où elles tirent plutôt sur le gris. Contrairement à la majorité de leurs congénères qui se déplacent en volant, les dragons de roche préfèrent creuser des galeries souterraines. C’est pourquoi les nains et les gnomes, qui accomplissent des travaux d’excavation dans les montagnes, ont plus de chances d’en rencontrer. Et quand des nains bornés tombent sur des dragons bruns aussi entêtés, le conflit est souvent inévitable.<br>Le dragon brun peut s’enfouir dans le sable, le sol meuble, la terre compacte et la roche en se déplaçant à la même vitesse qu’avec une action de mouvement normale. Quand il est sous terre, le dragon brun peut se secouer pour obliger toutes les créatures dans un rayon de 30 mètres à faire un jet d’Athlétisme ou de Physique (SD 25). En cas d’échec, les cibles se retrouvent au sol et doivent faire un jet de sauvegarde d’étourdissement avec un malus de –3. Enfin, le dragon peut utiliser son round complet pour jaillir du sol, forçant les personnages à 10 mètres de lui à effectuer un jet de défense (SD 25). En cas d’échec, la cible est projetée 6 mètres plus loin et subit 6d6 dégâts au torse."
	  },
	  {
		"Nom": "DRAGON BLANC",
			  "Type": "DRACONIDE",
		"Menace": "Légendaire Complexe",
		"Récompense": "5 000 couronnes",
		"Armure": "25",
		"Taille": "12 m",
		"Poids": "800 kg",
		"Environnement": ["Forêts"],
		"Intelligence": "Pensant",
		"Organisation": "Solitaire",
		"Note": "Quantité d’érudits se demandent si les dragons blancs ne sont pas un mythe concocté par les explorateurs qui s’aventurèrent au nord des monts du Dragon. Ces quadrupèdes ailés seraient revêtus d’écailles oscillant entre le bleu et le gris clair, leur corps élancé coiffé d’une tête surmontée d’une crête. Les dragons blancs qui parcourent les forêts enneigées et les vallées du Nord lointain inspirent le respect aux autochtones de ces régions. Ils sont plutôt grands, environ douze mètres de long, et leur souffle semblable au blizzard hivernal emprisonne les êtres vivants et les objets dans une épaisse couche de glace. Cette espèce a pu être observée dans les monts des Dragons, mais jamais à l’intérieur des frontières des Royaumes du Nord. À l’évidence, elle préfère les étendues sauvages balayées par les vents du septentrion et ne supporterait pas les températures plus tempérées de la Rédania, sans parler du climat tropical qui règne au sud de Nilfgaard.<br>Au lieu d’infliger des dégâts de feu et d’enflammer ses victimes, le souffle d’un dragon blanc inflige 7d6 dégâts de glace et emprisonne les cibles qui ratent leur action de défense dans une gangue de glace. Les victimes immobilisées ne peuvent plus tenter d’action. Pour briser la glace, il faut réussir un jet de Physique (SD 25). Sinon, un personnage peut libérer la cible en infligeant 10 points de dégâts à la glace, ou 5 points de dégâts de feu. Les dégâts excédentaires, qui dépassent les 10 ou 5 points requis, sont reportés sur une partie du corps de la cible choisie au hasard."
	  },
	  {
    "Nom": "VAMPIRE SUPÉRIEUR",
		  "Type": "VAMPIRE",
    "Menace": "Légendaire Complexe",
    "Récompense": "5 000 couronnes",
    "Armure": "8",
    "Taille": "1.8 m",
    "Poids": "75 kg",
    "Environnement": ["Ville"],
    "Intelligence": "Pensant",
    "Organisation": "Solitaire",
    "Note": ""
  }

	]
}
